defmodule QuickBEAM.VM.Builtin do
  @moduledoc """
  Macros and helpers for defining JS builtins in all contexts.

  All builtins use 2-arity `fn args, this ->` convention.

  ## Module-level dispatch (generates def clauses)

      proto "push" do ... end         # → def proto_property("push")
      static "isArray" do ... end     # → def static_property("isArray")
      constant "PI", :math.pi()      # → def static_property("PI"), do: value

  ## Named object (generates def object/0)

      js_object "Math" do
        method "floor" do ... end
        val "PI", :math.pi()
      end

  ## Inline maps and objects

      build_methods do              # returns %{"name" => {:builtin, ...}, ...}
        method "add" do ... end
        args_method "from", &from_args/1
        receiver_method "slice", &slice/2
        this_method "toJSON", &to_json/1
        symbol :iterator do
          method do ... end
        end
        accessor "size" do
          get do ... end
        end
        prop "size", 0
      end

      object do                     # returns Heap.wrap(%{"name" => {:builtin, ...}, ...})
        prop "type", type
        method "preventDefault" do ... end
      end

      object heap: false do         # returns the raw map for post-processing
        prop "searchParams", search_params
      end

      constructor "DOMException", &build_dom_exception/2 do
        proto do
          extends build_error_proto()
        end
      end

  `args` and `this` are injected in all `proto`/`static`/`method` bodies.
  `arg/3`, `argv/2`, `builtin_*`, and `iterator_from/1` cover the repeated
  argument-defaulting, function-wrapping, and iterator boilerplate used by Web APIs.
  Catch-all fallbacks are auto-generated by @before_compile.
  """

  alias QuickBEAM.VM.Heap
  alias QuickBEAM.VM.ObjectModel.PropertyDescriptor

  defmodule FunctionSpec do
    @moduledoc "Declarative metadata for an ECMAScript builtin function."

    defstruct name: nil,
              length: 0,
              kind: :function,
              constructable?: false,
              writable?: true,
              enumerable?: false,
              configurable?: true,
              ecma: nil,
              annex: nil
  end

  defmodule PropertySpec do
    @moduledoc "Declarative metadata for an ECMAScript builtin property."

    defstruct key: nil,
              kind: :data,
              value: nil,
              descriptor: %{},
              ecma: nil,
              annex: nil
  end

  defmodule ObjectSpec do
    @moduledoc "Declarative metadata for an ECMAScript builtin object."

    defstruct name: nil,
              intrinsic: nil,
              properties: [],
              prototype: nil,
              ecma: nil,
              annex: nil
  end

  defmodule IntrinsicSpec do
    @moduledoc "Declarative metadata for an ECMAScript intrinsic graph entry."

    defstruct name: nil,
              constructor: nil,
              statics: [],
              prototype: nil,
              definition: nil,
              ecma: nil,
              annex: nil
  end

  defmodule Meta do
    @moduledoc "Metadata attached to JavaScript builtin functions and properties."

    defstruct name: nil,
              length: 0,
              constructable?: false,
              writable?: true,
              enumerable?: false,
              configurable?: true,
              kind: :function,
              ecma: nil,
              annex: nil
  end

  @doc "Builds builtin metadata from macro options."
  def meta(name, opts \\ [], kind \\ :function) do
    name
    |> function_spec(opts, kind)
    |> function_meta()
  end

  def function_meta(%FunctionSpec{} = spec) do
    %Meta{
      name: spec.name,
      length: spec.length,
      constructable?: spec.constructable?,
      writable?: spec.writable?,
      enumerable?: spec.enumerable?,
      configurable?: spec.configurable?,
      kind: spec.kind,
      ecma: spec.ecma,
      annex: spec.annex
    }
  end

  @doc "Builds a declarative accessor property spec."
  def accessor_property_spec(key, getter, setter \\ nil, opts \\ []) do
    %PropertySpec{
      key: key,
      kind: :accessor,
      value: {:accessor, getter, setter},
      descriptor: %{
        enumerable: Keyword.get(opts, :enumerable, false),
        configurable: Keyword.get(opts, :configurable, true)
      },
      ecma: Keyword.get(opts, :ecma),
      annex: Keyword.get(opts, :annex)
    }
  end

  @doc "Builds a declarative data property spec."
  def data_property_spec(key, value, opts \\ []) do
    %PropertySpec{
      key: key,
      kind: :data,
      value: value,
      descriptor: descriptor_from_opts(opts),
      ecma: Keyword.get(opts, :ecma),
      annex: Keyword.get(opts, :annex)
    }
  end

  @doc "Builds a declarative property spec for a builtin function property."
  def property_spec(key, %FunctionSpec{} = function_spec) do
    %PropertySpec{
      key: key,
      kind: function_spec.kind,
      value: function_spec,
      descriptor: %{
        writable: function_spec.writable?,
        enumerable: function_spec.enumerable?,
        configurable: function_spec.configurable?
      },
      ecma: function_spec.ecma,
      annex: function_spec.annex
    }
  end

  defp descriptor_from_opts(opts) do
    %{
      writable: Keyword.get(opts, :writable, true),
      enumerable: Keyword.get(opts, :enumerable, false),
      configurable: Keyword.get(opts, :configurable, true)
    }
  end

  @doc "Builds a first-class function spec from builtin macro options."
  def function_spec(name, opts \\ [], kind \\ :function) do
    %FunctionSpec{
      name: Keyword.get(opts, :name, name),
      length: Keyword.get(opts, :length, 0),
      constructable?: Keyword.get(opts, :constructable, false),
      writable?: Keyword.get(opts, :writable, true),
      enumerable?: Keyword.get(opts, :enumerable, false),
      configurable?: Keyword.get(opts, :configurable, true),
      kind: kind,
      ecma: Keyword.get(opts, :ecma),
      annex: Keyword.get(opts, :annex)
    }
  end

  @doc "Builds an intrinsic spec for a runtime module and builtin definition."
  def intrinsic_spec(module, definition) when is_atom(module) do
    proto_specs = module_property_specs(module, :proto)
    static_specs = module_property_specs(module, :static)

    %IntrinsicSpec{
      name: definition.name,
      definition: definition,
      constructor:
        function_spec(definition.name,
          length: definition.length || 0,
          constructable: definition.constructable?,
          ecma: definition.ecma,
          annex: definition.annex
        ),
      statics: static_specs,
      prototype: %ObjectSpec{
        name: definition.name <> ".prototype",
        properties: proto_specs,
        ecma: definition.ecma,
        annex: definition.annex
      },
      ecma: definition.ecma,
      annex: definition.annex
    }
  end

  defp module_property_specs(module, kind) do
    names_fun = if kind == :proto, do: :proto_property_names, else: :static_property_names
    spec_fun = if kind == :proto, do: :proto_property_spec, else: :static_property_spec

    if function_exported?(module, names_fun, 0) do
      module
      |> apply(names_fun, [])
      |> Enum.map(fn name -> module |> apply(spec_fun, [name]) |> maybe_property_spec(name) end)
      |> Enum.reject(&is_nil/1)
    else
      []
    end
  end

  defp maybe_property_spec(nil, _key), do: nil
  defp maybe_property_spec(%FunctionSpec{} = spec, key), do: property_spec(key, spec)
  defp maybe_property_spec(%PropertySpec{} = spec, _key), do: spec

  @doc "Returns metadata for a module-level static builtin, when the module declares it."
  def static_meta(module, name) when is_atom(module) do
    if function_exported?(module, :static_property_meta, 1), do: module.static_property_meta(name)
  end

  @doc "Returns metadata for a module-level prototype builtin, when the module declares it."
  def proto_meta(module, name) when is_atom(module) do
    if function_exported?(module, :proto_property_meta, 1), do: module.proto_property_meta(name)
  end

  @doc "Returns whether builtin metadata marks a value as constructable."
  def constructable?(%Meta{constructable?: constructable?}), do: constructable?
  def constructable?(_), do: false

  @doc "Returns the declared length from builtin metadata or zero."
  def length(%Meta{length: length}), do: length
  def length(_), do: 0

  @doc "Returns metadata attached to a builtin function, falling back to built-in name metadata."
  def metadata_for({:builtin, name, _} = builtin) do
    Map.get(Heap.get_ctor_statics(builtin), :__builtin_meta__) || named_meta(name)
  end

  def metadata_for(name) when is_binary(name), do: named_meta(name)
  def metadata_for(_), do: nil

  @doc "Returns the declared builtin length or the supplied default."
  def declared_length(value, default \\ :undefined) do
    case metadata_for(value) do
      %Meta{length: length} -> length
      _ -> default
    end
  end

  @doc "Stores internal builtin metadata on a callable or constructor."
  def put_builtin_metadata(function, %Meta{} = meta) do
    Heap.put_ctor_static(function, :__builtin_meta__, meta)
    function
  end

  @doc "Stores JavaScript-visible function name and length metadata."
  def put_function_metadata(function, name, length) do
    Heap.put_ctor_static(function, "length", length)
    Heap.put_ctor_static(function, "name", name)
    function
  end

  @doc "Returns built-in function metadata by JavaScript-visible function name."
  def named_meta("Object"), do: meta("Object", [length: 1, constructable: true], :constructor)
  def named_meta("Function"), do: meta("Function", [length: 1, constructable: true], :constructor)
  def named_meta("String"), do: meta("String", [length: 1, constructable: true], :constructor)
  def named_meta("Number"), do: meta("Number", [length: 1, constructable: true], :constructor)
  def named_meta("Array"), do: meta("Array", [length: 1, constructable: true], :constructor)
  def named_meta("Boolean"), do: meta("Boolean", [length: 1, constructable: true], :constructor)
  def named_meta("RegExp"), do: meta("RegExp", [length: 2, constructable: true], :constructor)
  def named_meta("Date"), do: meta("Date", [length: 7, constructable: true], :constructor)
  def named_meta("Promise"), do: meta("Promise", [length: 1, constructable: true], :constructor)

  def named_meta("ArrayBuffer"),
    do: meta("ArrayBuffer", [length: 1, constructable: true], :constructor)

  def named_meta("SharedArrayBuffer"),
    do: meta("SharedArrayBuffer", [length: 1, constructable: true], :constructor)

  def named_meta("DataView"), do: meta("DataView", [length: 1, constructable: true], :constructor)
  def named_meta("Error"), do: meta("Error", [length: 1, constructable: true], :constructor)

  def named_meta("AggregateError"),
    do: meta("AggregateError", [length: 2, constructable: true], :constructor)

  def named_meta("SuppressedError"),
    do: meta("SuppressedError", [length: 3, constructable: true], :constructor)

  def named_meta("EvalError"),
    do: meta("EvalError", [length: 1, constructable: true], :constructor)

  def named_meta("RangeError"),
    do: meta("RangeError", [length: 1, constructable: true], :constructor)

  def named_meta("ReferenceError"),
    do: meta("ReferenceError", [length: 1, constructable: true], :constructor)

  def named_meta("SyntaxError"),
    do: meta("SyntaxError", [length: 1, constructable: true], :constructor)

  def named_meta("TypeError"),
    do: meta("TypeError", [length: 1, constructable: true], :constructor)

  def named_meta("URIError"), do: meta("URIError", [length: 1, constructable: true], :constructor)
  def named_meta("Map"), do: meta("Map", [length: 0, constructable: true], :constructor)
  def named_meta("Set"), do: meta("Set", [length: 0, constructable: true], :constructor)
  def named_meta("WeakMap"), do: meta("WeakMap", [length: 0, constructable: true], :constructor)
  def named_meta("WeakSet"), do: meta("WeakSet", [length: 0, constructable: true], :constructor)
  def named_meta("WeakRef"), do: meta("WeakRef", [length: 1, constructable: true], :constructor)

  def named_meta("FinalizationRegistry"),
    do: meta("FinalizationRegistry", [length: 1, constructable: true], :constructor)

  def named_meta("assign"), do: meta("assign", [length: 2, constructable: false], :static)
  def named_meta("create"), do: meta("create", [length: 2, constructable: false], :static)

  def named_meta("defineProperty"),
    do: meta("defineProperty", [length: 3, constructable: false], :static)

  def named_meta("defineProperties"),
    do: meta("defineProperties", [length: 2, constructable: false], :static)

  def named_meta("getOwnPropertyDescriptor"),
    do: meta("getOwnPropertyDescriptor", [length: 2, constructable: false], :static)

  def named_meta(name)
      when name in [
             "getOwnPropertyDescriptors",
             "getOwnPropertyNames",
             "getOwnPropertySymbols",
             "getPrototypeOf"
           ],
      do: meta(name, [length: 1, constructable: false], :static)

  def named_meta("hasOwn"), do: meta("hasOwn", [length: 2, constructable: false], :static)
  def named_meta("groupBy"), do: meta("groupBy", [length: 2, constructable: false], :static)
  def named_meta("is"), do: meta("is", [length: 2, constructable: false], :static)

  def named_meta("parse"), do: meta("parse", [length: 2, constructable: false], :static)
  def named_meta("stringify"), do: meta("stringify", [length: 3, constructable: false], :static)
  def named_meta("rawJSON"), do: meta("rawJSON", [length: 1, constructable: false], :static)
  def named_meta("isRawJSON"), do: meta("isRawJSON", [length: 1, constructable: false], :static)

  def named_meta(name)
      when name in [
             "abs",
             "acos",
             "acosh",
             "asin",
             "asinh",
             "atan",
             "atan2",
             "atanh",
             "cbrt",
             "ceil",
             "clz32",
             "cos",
             "cosh",
             "exp",
             "expm1",
             "floor",
             "f16round",
             "fround",
             "hypot",
             "imul",
             "log",
             "log10",
             "log1p",
             "log2",
             "max",
             "min",
             "pow",
             "random",
             "round",
             "sign",
             "sin",
             "sinh",
             "sqrt",
             "sumPrecise",
             "tan",
             "tanh",
             "trunc"
           ],
      do:
        meta(
          name,
          [
            length:
              cond do
                name in ["atan2", "hypot", "imul", "max", "min", "pow"] -> 2
                name == "random" -> 0
                true -> 1
              end,
            constructable: false
          ],
          :static
        )

  def named_meta("getOwnPropertyDescriptor"),
    do: meta("getOwnPropertyDescriptor", [length: 2, constructable: false], :static)

  def named_meta("getOwnPropertyNames"),
    do: meta("getOwnPropertyNames", [length: 1, constructable: false], :static)

  def named_meta("getOwnPropertyDescriptors"),
    do: meta("getOwnPropertyDescriptors", [length: 1, constructable: false], :static)

  def named_meta("getPrototypeOf"),
    do: meta("getPrototypeOf", [length: 1, constructable: false], :static)

  def named_meta("construct"), do: meta("construct", [length: 2, constructable: false], :static)

  def named_meta("deleteProperty"),
    do: meta("deleteProperty", [length: 2, constructable: false], :static)

  def named_meta("ownKeys"), do: meta("ownKeys", [length: 1, constructable: false], :static)

  def named_meta("setPrototypeOf"),
    do: meta("setPrototypeOf", [length: 2, constructable: false], :static)

  def named_meta("keys"), do: meta("keys", [length: 1, constructable: false], :static)
  def named_meta("values"), do: meta("values", [length: 1, constructable: false], :static)
  def named_meta("entries"), do: meta("entries", [length: 1, constructable: false], :static)
  def named_meta("escape"), do: meta("escape", [length: 1, constructable: false], :static)
  def named_meta("freeze"), do: meta("freeze", [length: 1, constructable: false], :static)

  def named_meta("preventExtensions"),
    do: meta("preventExtensions", [length: 1, constructable: false], :static)

  def named_meta("seal"), do: meta("seal", [length: 1, constructable: false], :static)
  def named_meta("isFrozen"), do: meta("isFrozen", [length: 1, constructable: false], :static)
  def named_meta("isSealed"), do: meta("isSealed", [length: 1, constructable: false], :static)

  def named_meta("isExtensible"),
    do: meta("isExtensible", [length: 1, constructable: false], :static)

  def named_meta("fromEntries"),
    do: meta("fromEntries", [length: 1, constructable: false], :static)

  def named_meta("__defineGetter__"),
    do: meta("__defineGetter__", [length: 2, constructable: false], :proto)

  def named_meta("__defineSetter__"),
    do: meta("__defineSetter__", [length: 2, constructable: false], :proto)

  def named_meta("__lookupGetter__"),
    do: meta("__lookupGetter__", [length: 1, constructable: false], :proto)

  def named_meta("__lookupSetter__"),
    do: meta("__lookupSetter__", [length: 1, constructable: false], :proto)

  def named_meta("get __proto__"),
    do: meta("get __proto__", [length: 0, constructable: false], :proto)

  def named_meta("set __proto__"),
    do: meta("set __proto__", [length: 1, constructable: false], :proto)

  def named_meta("call"), do: meta("call", [length: 1, constructable: false], :proto)
  def named_meta("apply"), do: meta("apply", [length: 2, constructable: false], :proto)
  def named_meta("bind"), do: meta("bind", [length: 1, constructable: false], :proto)

  def named_meta("[Symbol.hasInstance]"),
    do: meta("[Symbol.hasInstance]", [length: 1, constructable: false], :proto)

  def named_meta("setTime"), do: meta("setTime", [length: 1, constructable: false], :proto)

  def named_meta("setFullYear"),
    do: meta("setFullYear", [length: 3, constructable: false], :proto)

  def named_meta("setMonth"), do: meta("setMonth", [length: 2, constructable: false], :proto)
  def named_meta("setDate"), do: meta("setDate", [length: 1, constructable: false], :proto)
  def named_meta("setHours"), do: meta("setHours", [length: 4, constructable: false], :proto)
  def named_meta("setMinutes"), do: meta("setMinutes", [length: 3, constructable: false], :proto)
  def named_meta("setSeconds"), do: meta("setSeconds", [length: 2, constructable: false], :proto)

  def named_meta("setMilliseconds"),
    do: meta("setMilliseconds", [length: 1, constructable: false], :proto)

  def named_meta("setUTCFullYear"),
    do: meta("setUTCFullYear", [length: 3, constructable: false], :proto)

  def named_meta("setUTCMonth"),
    do: meta("setUTCMonth", [length: 2, constructable: false], :proto)

  def named_meta("setUTCDate"), do: meta("setUTCDate", [length: 1, constructable: false], :proto)

  def named_meta("setUTCHours"),
    do: meta("setUTCHours", [length: 4, constructable: false], :proto)

  def named_meta("setUTCMinutes"),
    do: meta("setUTCMinutes", [length: 3, constructable: false], :proto)

  def named_meta("setUTCSeconds"),
    do: meta("setUTCSeconds", [length: 2, constructable: false], :proto)

  def named_meta("setUTCMilliseconds"),
    do: meta("setUTCMilliseconds", [length: 1, constructable: false], :proto)

  def named_meta("getTime"), do: meta("getTime", [length: 0, constructable: false], :proto)

  def named_meta("getFullYear"),
    do: meta("getFullYear", [length: 0, constructable: false], :proto)

  def named_meta("getMonth"), do: meta("getMonth", [length: 0, constructable: false], :proto)
  def named_meta("getDate"), do: meta("getDate", [length: 0, constructable: false], :proto)
  def named_meta("getHours"), do: meta("getHours", [length: 0, constructable: false], :proto)
  def named_meta("getMinutes"), do: meta("getMinutes", [length: 0, constructable: false], :proto)
  def named_meta("getSeconds"), do: meta("getSeconds", [length: 0, constructable: false], :proto)

  def named_meta("getMilliseconds"),
    do: meta("getMilliseconds", [length: 0, constructable: false], :proto)

  def named_meta("getDay"), do: meta("getDay", [length: 0, constructable: false], :proto)

  def named_meta("getTimezoneOffset"),
    do: meta("getTimezoneOffset", [length: 0, constructable: false], :proto)

  def named_meta("getUTCFullYear"),
    do: meta("getUTCFullYear", [length: 0, constructable: false], :proto)

  def named_meta("getUTCMonth"),
    do: meta("getUTCMonth", [length: 0, constructable: false], :proto)

  def named_meta("getUTCDate"), do: meta("getUTCDate", [length: 0, constructable: false], :proto)
  def named_meta("getUTCDay"), do: meta("getUTCDay", [length: 0, constructable: false], :proto)

  def named_meta("getUTCHours"),
    do: meta("getUTCHours", [length: 0, constructable: false], :proto)

  def named_meta("getUTCMinutes"),
    do: meta("getUTCMinutes", [length: 0, constructable: false], :proto)

  def named_meta("getUTCSeconds"),
    do: meta("getUTCSeconds", [length: 0, constructable: false], :proto)

  def named_meta("getUTCMilliseconds"),
    do: meta("getUTCMilliseconds", [length: 0, constructable: false], :proto)

  def named_meta("valueOf"), do: meta("valueOf", [length: 0, constructable: false], :proto)
  def named_meta("toString"), do: meta("toString", [length: 0, constructable: false], :proto)
  def named_meta("toReversed"), do: meta("toReversed", [length: 0, constructable: false], :proto)
  def named_meta("toSorted"), do: meta("toSorted", [length: 1, constructable: false], :proto)
  def named_meta("toSpliced"), do: meta("toSpliced", [length: 2, constructable: false], :proto)
  def named_meta("with"), do: meta("with", [length: 2, constructable: false], :proto)

  def named_meta("toISOString"),
    do: meta("toISOString", [length: 0, constructable: false], :proto)

  def named_meta("toJSON"), do: meta("toJSON", [length: 1, constructable: false], :proto)

  def named_meta("toDateString"),
    do: meta("toDateString", [length: 0, constructable: false], :proto)

  def named_meta("toTimeString"),
    do: meta("toTimeString", [length: 0, constructable: false], :proto)

  def named_meta("toUTCString"),
    do: meta("toUTCString", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleString"),
    do: meta("toLocaleString", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleDateString"),
    do: meta("toLocaleDateString", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleTimeString"),
    do: meta("toLocaleTimeString", [length: 0, constructable: false], :proto)

  def named_meta("now"), do: meta("now", [length: 0, constructable: false], :static)
  def named_meta("parse"), do: meta("parse", [length: 1, constructable: false], :static)
  def named_meta("UTC"), do: meta("UTC", [length: 7, constructable: false], :static)

  def named_meta("isFinite"), do: meta("isFinite", [length: 1, constructable: false], :static)
  def named_meta("isInteger"), do: meta("isInteger", [length: 1, constructable: false], :static)
  def named_meta("isNaN"), do: meta("isNaN", [length: 1, constructable: false], :static)

  def named_meta("isSafeInteger"),
    do: meta("isSafeInteger", [length: 1, constructable: false], :static)

  def named_meta("toFixed"), do: meta("toFixed", [length: 1, constructable: false], :proto)

  def named_meta("toExponential"),
    do: meta("toExponential", [length: 1, constructable: false], :proto)

  def named_meta("toPrecision"),
    do: meta("toPrecision", [length: 1, constructable: false], :proto)

  def named_meta("parseFloat"), do: meta("parseFloat", [length: 1, constructable: false], :static)
  def named_meta("parseInt"), do: meta("parseInt", [length: 2, constructable: false], :static)

  def named_meta("charAt"), do: meta("charAt", [length: 1, constructable: false], :proto)
  def named_meta("charCodeAt"), do: meta("charCodeAt", [length: 1, constructable: false], :proto)

  def named_meta("codePointAt"),
    do: meta("codePointAt", [length: 1, constructable: false], :proto)

  def named_meta("indexOf"), do: meta("indexOf", [length: 1, constructable: false], :proto)

  def named_meta("lastIndexOf"),
    do: meta("lastIndexOf", [length: 1, constructable: false], :proto)

  def named_meta("includes"), do: meta("includes", [length: 1, constructable: false], :proto)
  def named_meta("startsWith"), do: meta("startsWith", [length: 1, constructable: false], :proto)
  def named_meta("endsWith"), do: meta("endsWith", [length: 1, constructable: false], :proto)
  def named_meta("slice"), do: meta("slice", [length: 2, constructable: false], :proto)
  def named_meta("subarray"), do: meta("subarray", [length: 2, constructable: false], :proto)
  def named_meta("splice"), do: meta("splice", [length: 2, constructable: false], :proto)
  def named_meta("substring"), do: meta("substring", [length: 2, constructable: false], :proto)
  def named_meta("substr"), do: meta("substr", [length: 2, constructable: false], :proto)
  def named_meta("split"), do: meta("split", [length: 2, constructable: false], :proto)

  def named_meta("[Symbol.split]"),
    do: meta("[Symbol.split]", [length: 2, constructable: false], :proto)

  def named_meta("trim"), do: meta("trim", [length: 0, constructable: false], :proto)
  def named_meta("trimStart"), do: meta("trimStart", [length: 0, constructable: false], :proto)
  def named_meta("trimEnd"), do: meta("trimEnd", [length: 0, constructable: false], :proto)

  def named_meta("toUpperCase"),
    do: meta("toUpperCase", [length: 0, constructable: false], :proto)

  def named_meta("toLowerCase"),
    do: meta("toLowerCase", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleUpperCase"),
    do: meta("toLocaleUpperCase", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleLowerCase"),
    do: meta("toLocaleLowerCase", [length: 0, constructable: false], :proto)

  def named_meta("repeat"), do: meta("repeat", [length: 1, constructable: false], :proto)
  def named_meta("padStart"), do: meta("padStart", [length: 1, constructable: false], :proto)
  def named_meta("padEnd"), do: meta("padEnd", [length: 1, constructable: false], :proto)
  def named_meta("replace"), do: meta("replace", [length: 2, constructable: false], :proto)

  def named_meta("[Symbol.replace]"),
    do: meta("[Symbol.replace]", [length: 2, constructable: false], :proto)

  def named_meta("replaceAll"), do: meta("replaceAll", [length: 2, constructable: false], :proto)
  def named_meta("match"), do: meta("match", [length: 1, constructable: false], :proto)

  def named_meta("[Symbol.match]"),
    do: meta("[Symbol.match]", [length: 1, constructable: false], :proto)

  def named_meta("matchAll"), do: meta("matchAll", [length: 1, constructable: false], :proto)

  def named_meta("[Symbol.matchAll]"),
    do: meta("[Symbol.matchAll]", [length: 1, constructable: false], :proto)

  def named_meta("search"), do: meta("search", [length: 1, constructable: false], :proto)

  def named_meta("[Symbol.search]"),
    do: meta("[Symbol.search]", [length: 1, constructable: false], :proto)

  def named_meta("normalize"), do: meta("normalize", [length: 0, constructable: false], :proto)
  def named_meta("concat"), do: meta("concat", [length: 1, constructable: false], :proto)

  def named_meta("localeCompare"),
    do: meta("localeCompare", [length: 1, constructable: false], :proto)

  def named_meta("at"), do: meta("at", [length: 1, constructable: false], :proto)

  def named_meta("isWellFormed"),
    do: meta("isWellFormed", [length: 0, constructable: false], :proto)

  def named_meta("toWellFormed"),
    do: meta("toWellFormed", [length: 0, constructable: false], :proto)

  def named_meta("fromCharCode"),
    do: meta("fromCharCode", [length: 1, constructable: false], :static)

  def named_meta("fromCodePoint"),
    do: meta("fromCodePoint", [length: 1, constructable: false], :static)

  def named_meta("raw"), do: meta("raw", [length: 1, constructable: false], :static)

  def named_meta("[Symbol.iterator]"),
    do: meta("[Symbol.iterator]", [length: 0, constructable: false], :proto)

  def named_meta("get flags"), do: meta("get flags", [length: 0, constructable: false], :proto)

  def named_meta("get hasIndices"),
    do: meta("get hasIndices", [length: 0, constructable: false], :proto)

  def named_meta("get global"), do: meta("get global", [length: 0, constructable: false], :proto)

  def named_meta("get ignoreCase"),
    do: meta("get ignoreCase", [length: 0, constructable: false], :proto)

  def named_meta("get multiline"),
    do: meta("get multiline", [length: 0, constructable: false], :proto)

  def named_meta("get dotAll"), do: meta("get dotAll", [length: 0, constructable: false], :proto)

  def named_meta("get unicode"),
    do: meta("get unicode", [length: 0, constructable: false], :proto)

  def named_meta("get unicodeSets"),
    do: meta("get unicodeSets", [length: 0, constructable: false], :proto)

  def named_meta("get sticky"), do: meta("get sticky", [length: 0, constructable: false], :proto)

  def named_meta("exec"), do: meta("exec", [length: 1, constructable: false], :proto)
  def named_meta("test"), do: meta("test", [length: 1, constructable: false], :proto)

  def named_meta("push"), do: meta("push", [length: 1, constructable: false], :proto)
  def named_meta("pop"), do: meta("pop", [length: 0, constructable: false], :proto)
  def named_meta("shift"), do: meta("shift", [length: 0, constructable: false], :proto)
  def named_meta("unshift"), do: meta("unshift", [length: 1, constructable: false], :proto)
  def named_meta("map"), do: meta("map", [length: 1, constructable: false], :proto)
  def named_meta("filter"), do: meta("filter", [length: 1, constructable: false], :proto)
  def named_meta("reduce"), do: meta("reduce", [length: 1, constructable: false], :proto)

  def named_meta("reduceRight"),
    do: meta("reduceRight", [length: 1, constructable: false], :proto)

  def named_meta("forEach"), do: meta("forEach", [length: 1, constructable: false], :proto)
  def named_meta("some"), do: meta("some", [length: 1, constructable: false], :proto)
  def named_meta("every"), do: meta("every", [length: 1, constructable: false], :proto)
  def named_meta("find"), do: meta("find", [length: 1, constructable: false], :proto)
  def named_meta("findIndex"), do: meta("findIndex", [length: 1, constructable: false], :proto)
  def named_meta("findLast"), do: meta("findLast", [length: 1, constructable: false], :proto)

  def named_meta("findLastIndex"),
    do: meta("findLastIndex", [length: 1, constructable: false], :proto)

  def named_meta("sort"), do: meta("sort", [length: 1, constructable: false], :proto)
  def named_meta("reverse"), do: meta("reverse", [length: 0, constructable: false], :proto)
  def named_meta("join"), do: meta("join", [length: 1, constructable: false], :proto)
  def named_meta("fill"), do: meta("fill", [length: 1, constructable: false], :proto)
  def named_meta("copyWithin"), do: meta("copyWithin", [length: 2, constructable: false], :proto)
  def named_meta("flat"), do: meta("flat", [length: 0, constructable: false], :proto)
  def named_meta("flatMap"), do: meta("flatMap", [length: 1, constructable: false], :proto)
  def named_meta("drop"), do: meta("drop", [length: 1, constructable: false], :proto)
  def named_meta("take"), do: meta("take", [length: 1, constructable: false], :proto)
  def named_meta("toArray"), do: meta("toArray", [length: 0, constructable: false], :proto)
  def named_meta("zip"), do: meta("zip", [length: 1, constructable: false], :static)
  def named_meta("zipKeyed"), do: meta("zipKeyed", [length: 1, constructable: false], :static)
  def named_meta("from"), do: meta("from", [length: 1, constructable: false], :static)
  def named_meta("fromAsync"), do: meta("fromAsync", [length: 1, constructable: false], :static)
  def named_meta("of"), do: meta("of", [length: 0, constructable: false], :static)
  def named_meta("isArray"), do: meta("isArray", [length: 1, constructable: false], :static)
  def named_meta("groupBy"), do: meta("groupBy", [length: 2, constructable: false], :static)
  def named_meta("get"), do: meta("get", [length: 1, constructable: false], :proto)
  def named_meta("set"), do: meta("set", [length: 2, constructable: false], :proto)
  def named_meta("has"), do: meta("has", [length: 1, constructable: false], :proto)
  def named_meta("then"), do: meta("then", [length: 2, constructable: false], :proto)
  def named_meta("catch"), do: meta("catch", [length: 1, constructable: false], :proto)
  def named_meta("finally"), do: meta("finally", [length: 1, constructable: false], :proto)
  def named_meta("resolve"), do: meta("resolve", [length: 1, constructable: false], :static)
  def named_meta("reject"), do: meta("reject", [length: 1, constructable: false], :static)
  def named_meta("all"), do: meta("all", [length: 1, constructable: false], :static)
  def named_meta("allKeyed"), do: meta("allKeyed", [length: 1, constructable: false], :static)
  def named_meta("allSettled"), do: meta("allSettled", [length: 1, constructable: false], :static)

  def named_meta("allSettledKeyed"),
    do: meta("allSettledKeyed", [length: 1, constructable: false], :static)

  def named_meta("any"), do: meta("any", [length: 1, constructable: false], :static)
  def named_meta("race"), do: meta("race", [length: 1, constructable: false], :static)
  def named_meta("try"), do: meta("try", [length: 1, constructable: false], :static)

  def named_meta("withResolvers"),
    do: meta("withResolvers", [length: 0, constructable: false], :static)

  def named_meta("__promiseCapabilityExecutor"),
    do: meta("__promiseCapabilityExecutor", [length: 2, constructable: false], :static)

  def named_meta("isError"), do: meta("isError", [length: 1, constructable: false], :static)

  def named_meta(name)
      when name in [
             "getBigInt64",
             "getBigUint64",
             "getFloat16",
             "getFloat32",
             "getFloat64",
             "getInt8",
             "getInt16",
             "getInt32",
             "getUint8",
             "getUint16",
             "getUint32"
           ],
      do: meta(name, [length: 1, constructable: false], :proto)

  def named_meta(name)
      when name in [
             "setBigInt64",
             "setBigUint64",
             "setFloat16",
             "setFloat32",
             "setFloat64",
             "setInt8",
             "setInt16",
             "setInt32",
             "setUint8",
             "setUint16",
             "setUint32"
           ],
      do: meta(name, [length: 2, constructable: false], :proto)

  def named_meta("next"), do: meta("next", [length: 0, constructable: false], :proto)
  def named_meta("delete"), do: meta("delete", [length: 1, constructable: false], :proto)
  def named_meta("clear"), do: meta("clear", [length: 0, constructable: false], :proto)
  def named_meta("deref"), do: meta("deref", [length: 0, constructable: false], :proto)
  def named_meta("register"), do: meta("register", [length: 2, constructable: false], :proto)
  def named_meta("unregister"), do: meta("unregister", [length: 1, constructable: false], :proto)

  def named_meta("getOrInsert"),
    do: meta("getOrInsert", [length: 2, constructable: false], :proto)

  def named_meta("getOrInsertComputed"),
    do: meta("getOrInsertComputed", [length: 2, constructable: false], :proto)

  def named_meta("add"), do: meta("add", [length: 1, constructable: false], :proto)
  def named_meta("difference"), do: meta("difference", [length: 1, constructable: false], :proto)

  def named_meta("intersection"),
    do: meta("intersection", [length: 1, constructable: false], :proto)

  def named_meta("union"), do: meta("union", [length: 1, constructable: false], :proto)

  def named_meta("symmetricDifference"),
    do: meta("symmetricDifference", [length: 1, constructable: false], :proto)

  def named_meta("isSubsetOf"), do: meta("isSubsetOf", [length: 1, constructable: false], :proto)

  def named_meta("isSupersetOf"),
    do: meta("isSupersetOf", [length: 1, constructable: false], :proto)

  def named_meta("isDisjointFrom"),
    do: meta("isDisjointFrom", [length: 1, constructable: false], :proto)

  def named_meta("hasOwnProperty"),
    do: meta("hasOwnProperty", [length: 1, constructable: false], :proto)

  def named_meta("isPrototypeOf"),
    do: meta("isPrototypeOf", [length: 1, constructable: false], :proto)

  def named_meta("propertyIsEnumerable"),
    do: meta("propertyIsEnumerable", [length: 1, constructable: false], :proto)

  def named_meta(_), do: nil

  defmacro __using__(_opts) do
    quote do
      @behaviour QuickBEAM.VM.Runtime.BuiltinObject

      import QuickBEAM.VM.Builtin,
        only: [
          proto: 2,
          proto: 3,
          static: 2,
          static: 3,
          static_data: 2,
          static_data: 3,
          static_constant: 2,
          static_constant: 3,
          constant: 2,
          constant: 3,
          proto_accessor: 2,
          proto_accessor: 3,
          static_accessor: 2,
          static_accessor: 3,
          proto_getter: 2,
          proto_getter: 3,
          static_getter: 2,
          static_getter: 3,
          symbol: 2,
          proto_data: 2,
          proto_data: 3,
          property: 2,
          property: 3,
          defintrinsic: 2,
          defintrinsic: 3,
          defintrinsics: 1,
          intrinsic: 2,
          intrinsic: 3,
          prototype: 2,
          prototype_object: 1,
          object_parent: 1,
          internal_slot: 2,
          slot: 2,
          to_string_tag: 1,
          properties: 0,
          prototype_specs: 0,
          constructor_link: 0,
          prototype_methods: 1,
          static_methods: 1,
          js_object: 2,
          build_methods: 1,
          build_object: 1,
          object: 1,
          object: 2,
          builtin_definition: 2,
          constructor: 2,
          constructor: 3,
          arg: 2,
          arg: 3,
          argv: 2,
          slot_key: 1,
          builtin: 2,
          builtin: 3,
          builtin_args: 2,
          builtin_receiver: 2,
          builtin_this: 2,
          iterator_from: 1
        ]

      Module.register_attribute(__MODULE__, :__has_proto, accumulate: false)
      Module.register_attribute(__MODULE__, :__has_static, accumulate: false)
      Module.register_attribute(__MODULE__, :__proto_names, accumulate: true)
      Module.register_attribute(__MODULE__, :__static_names, accumulate: true)
      Module.register_attribute(__MODULE__, :ecma, accumulate: false)
      Module.register_attribute(__MODULE__, :annex, accumulate: false)
      @before_compile QuickBEAM.VM.Builtin
    end
  end

  @doc "Emits fallback clauses for modules that define prototype or static properties."
  defmacro __before_compile__(env) do
    has_proto = Module.get_attribute(env.module, :__has_proto)
    has_static = Module.get_attribute(env.module, :__has_static)

    static_names =
      Module.get_attribute(env.module, :__static_names) |> Enum.reverse() |> Enum.uniq()

    proto_names =
      Module.get_attribute(env.module, :__proto_names) |> Enum.reverse() |> Enum.uniq()

    proto_fallback =
      if has_proto do
        quote do
          def proto_property(_), do: :undefined
          def proto_property_meta(_), do: nil
          def proto_property_spec(_), do: nil
        end
      end

    static_fallback =
      if has_static do
        quote do
          def static_property(_), do: :undefined
          def static_property_meta(_), do: nil
          def static_property_spec(_), do: nil
        end
      end

    proto_names_fun =
      if has_proto do
        quote do
          def proto_property_names, do: unquote(Macro.escape(proto_names))
        end
      end

    static_names_fun =
      if has_static do
        quote do
          def static_property_names, do: unquote(Macro.escape(static_names))
        end
      end

    [proto_fallback, static_fallback, proto_names_fun, static_names_fun]
    |> Enum.reject(&is_nil/1)
    |> case do
      [] -> nil
      blocks -> {:__block__, [], blocks}
    end
  end

  # ── Module-level dispatch macros ──

  def opts_with_builtin_attrs(opts, ecma, annex) do
    opts
    |> put_attr(:ecma, ecma)
    |> put_attr(:annex, annex)
  end

  defp put_attr(opts, _key, nil), do: opts
  defp put_attr(opts, key, value), do: Keyword.put_new(opts, key, value)

  @doc "Defines a prototype property as a JavaScript builtin function."
  defmacro proto(name, opts \\ [], do: body) do
    quote do
      @__has_proto true
      @__proto_names unquote(name)

      def proto_property(unquote(name)) do
        unquote(build_builtin(name, body, opts))
      end

      def proto_property_spec(unquote(name)) do
        QuickBEAM.VM.Builtin.function_spec(
          unquote(name),
          QuickBEAM.VM.Builtin.opts_with_builtin_attrs(
            unquote(Macro.escape(opts)),
            @ecma,
            @annex
          ),
          :prototype
        )
      end

      def proto_property_meta(unquote(name)) do
        proto_property_spec(unquote(name))
        |> QuickBEAM.VM.Builtin.function_meta()
      end

      @ecma nil
      @annex nil
    end
  end

  @doc "Defines a constructor/static property as a JavaScript builtin function."
  defmacro static(name, opts \\ [], do: body) do
    quote do
      @__has_static true
      @__static_names unquote(name)

      def static_property(unquote(name)) do
        unquote(build_builtin(name, body, opts))
      end

      def static_property_spec(unquote(name)) do
        QuickBEAM.VM.Builtin.function_spec(
          unquote(name),
          QuickBEAM.VM.Builtin.opts_with_builtin_attrs(
            unquote(Macro.escape(opts)),
            @ecma,
            @annex
          ),
          :static
        )
      end

      def static_property_meta(unquote(name)) do
        static_property_spec(unquote(name))
        |> QuickBEAM.VM.Builtin.function_meta()
      end

      @ecma nil
      @annex nil
    end
  end

  @doc "Defines a declarative data property entry inside an object/spec block."
  defmacro property(_name, _opts) do
    raise ArgumentError, "property/2 is only available inside builtin object/spec blocks"
  end

  defmacro property(_name, _opts, do: _block) do
    raise ArgumentError, "property/3 is only available inside builtin object/spec blocks"
  end

  @doc "Defines a prototype accessor property."
  defmacro proto_accessor(name, opts \\ [], do: block) do
    build_accessor_property(:proto, name, opts, block)
  end

  @doc "Defines a constructor/static accessor property."
  defmacro static_accessor(name, opts \\ [], do: block) do
    build_accessor_property(:static, name, opts, block)
  end

  @doc "Defines a prototype getter property."
  defmacro proto_getter(name, opts \\ [], do: body) do
    build_getter_property(:proto, name, opts, body)
  end

  @doc "Defines a constructor/static getter property."
  defmacro static_getter(name, opts \\ [], do: body) do
    build_getter_property(:static, name, opts, body)
  end

  @doc "Defines a prototype data property."
  defmacro proto_data(name, value, opts \\ []) do
    build_value_property(:proto, name, value, opts)
  end

  @doc "Defines a constructor/static data property."
  defmacro static_data(name, value, opts \\ []) do
    build_value_property(:static, name, value, opts)
  end

  @doc "Defines a non-writable, non-enumerable, non-configurable constructor constant."
  defmacro static_constant(name, value, opts \\ []) do
    opts = Keyword.merge([writable: false, enumerable: false, configurable: false], opts)
    build_value_property(:static, name, value, opts)
  end

  @doc "Defines a non-writable, non-enumerable, non-configurable constructor constant."
  defmacro constant(name, value, opts \\ []) do
    opts = Keyword.merge([writable: false, enumerable: false, configurable: false], opts)
    build_value_property(:static, name, value, opts)
  end

  defp build_value_property(:proto, name, value, opts) do
    quote do
      @__has_proto true
      @__proto_names unquote(name)

      def proto_property(unquote(name)), do: unquote(value)

      def proto_property_spec(unquote(name)) do
        QuickBEAM.VM.Builtin.data_property_spec(
          unquote(name),
          unquote(value),
          QuickBEAM.VM.Builtin.opts_with_builtin_attrs(unquote(Macro.escape(opts)), @ecma, @annex)
        )
      end

      @ecma nil
      @annex nil
    end
  end

  defp build_value_property(:static, name, value, opts) do
    quote do
      @__has_static true
      @__static_names unquote(name)

      def static_property(unquote(name)), do: unquote(value)

      def static_property_spec(unquote(name)) do
        QuickBEAM.VM.Builtin.data_property_spec(
          unquote(name),
          unquote(value),
          QuickBEAM.VM.Builtin.opts_with_builtin_attrs(unquote(Macro.escape(opts)), @ecma, @annex)
        )
      end

      @ecma nil
      @annex nil
    end
  end

  defp build_accessor_property(target, name, opts, block) do
    {getter, setter} = build_accessor_parts(name, block, opts)
    build_accessor_property(target, name, getter, setter, opts)
  end

  defp build_getter_property(target, name, opts, body) do
    build_accessor_property(
      target,
      name,
      build_builtin("get #{builtin_property_name(name)}", body, opts),
      nil,
      opts
    )
  end

  defp build_accessor_property(:proto, name, getter, setter, opts) do
    quote do
      @__has_proto true
      @__proto_names unquote(name)

      def proto_property(unquote(name)), do: {:accessor, unquote(getter), unquote(setter)}

      def proto_property_spec(unquote(name)) do
        QuickBEAM.VM.Builtin.accessor_property_spec(
          unquote(name),
          unquote(getter),
          unquote(setter),
          QuickBEAM.VM.Builtin.opts_with_builtin_attrs(unquote(Macro.escape(opts)), @ecma, @annex)
        )
      end

      @ecma nil
      @annex nil
    end
  end

  defp build_accessor_property(:static, name, getter, setter, opts) do
    quote do
      @__has_static true
      @__static_names unquote(name)

      def static_property(unquote(name)), do: {:accessor, unquote(getter), unquote(setter)}

      def static_property_spec(unquote(name)) do
        QuickBEAM.VM.Builtin.accessor_property_spec(
          unquote(name),
          unquote(getter),
          unquote(setter),
          QuickBEAM.VM.Builtin.opts_with_builtin_attrs(unquote(Macro.escape(opts)), @ecma, @annex)
        )
      end

      @ecma nil
      @annex nil
    end
  end

  @doc "Defines multiple ECMAScript intrinsic constructors from one runtime module."
  defmacro defintrinsics(do: block) do
    definitions =
      block
      |> normalize_block()
      |> Enum.map(&multi_intrinsic_definition(&1, __CALLER__))

    quote do
      def builtin_definitions do
        unquote(definitions)
      end
    end
  end

  defmacro intrinsic(_name, _opts) do
    raise ArgumentError, "intrinsic/2 is only available inside defintrinsics blocks"
  end

  defmacro intrinsic(_name, _opts, do: _block) do
    raise ArgumentError, "intrinsic/3 is only available inside defintrinsics blocks"
  end

  defp multi_intrinsic_definition({:intrinsic, _, [name, opts]}, caller) when is_list(opts) do
    build_definition_struct(name, opts, caller)
  end

  defp multi_intrinsic_definition({:intrinsic, _, [name, opts, [do: block]]}, caller)
       when is_list(opts) do
    {block_opts, declarations} = parse_intrinsic_block(block)

    if declarations != [] do
      raise ArgumentError,
            "intrinsic blocks inside defintrinsics currently support constructor/install metadata only"
    end

    build_definition_struct(name, Keyword.merge(opts, block_opts), caller)
  end

  defp multi_intrinsic_definition(other, _caller) do
    raise ArgumentError, "unsupported defintrinsics entry: #{Macro.to_string(other)}"
  end

  @doc "Defines an ECMAScript intrinsic constructor. Alias for `builtin_definition/2`."
  defmacro defintrinsic(name, opts) do
    case Keyword.pop(opts, :do) do
      {nil, opts} ->
        build_builtin_definition(name, opts, __CALLER__)

      {block, opts} ->
        build_intrinsic(name, opts, block, __CALLER__)
    end
  end

  defmacro defintrinsic(name, opts, do: block) do
    build_intrinsic(name, opts, block, __CALLER__)
  end

  defp build_intrinsic(name, opts, block, caller) do
    {block_opts, declarations} = parse_intrinsic_block(block)
    definition = build_builtin_definition(name, Keyword.merge(opts, block_opts), caller)

    quote do
      unquote(definition)
      unquote_splicing(declarations)
    end
  end

  @doc "Configures the intrinsic prototype object inside an install block."
  defmacro prototype(opts, do: block) when is_list(opts) do
    parent = Keyword.get(opts, :extends, :object)
    install_properties? = Keyword.get(opts, :properties, true)
    constructor_link? = Keyword.get(opts, :constructor_link, true)

    quote do
      QuickBEAM.VM.Runtime.InstallerHelpers.with_prototype(var!(ctor), fn var!(proto_ref) ->
        QuickBEAM.VM.Runtime.InstallerHelpers.install_object_parent(
          var!(proto_ref),
          unquote(prototype_parent(parent))
        )

        unquote(block)
        unquote(prototype_properties(install_properties?))
        unquote(prototype_constructor_link(constructor_link?))
      end)
    end
  end

  @doc "Runs an install block against the intrinsic prototype object."
  defmacro prototype_object(do: block) do
    quote do
      QuickBEAM.VM.Runtime.InstallerHelpers.with_prototype(var!(ctor), fn var!(proto_ref) ->
        unquote(block)
      end)
    end
  end

  defp prototype_parent(:object) do
    quote do
      Keyword.get(var!(opts), :object_proto, QuickBEAM.VM.Heap.get_object_prototype())
    end
  end

  defp prototype_parent(parent), do: parent

  defp prototype_properties(true) do
    quote do
      QuickBEAM.VM.Builtin.Installer.install_prototype_specs(var!(proto_ref), __MODULE__)
    end
  end

  defp prototype_properties(false), do: nil

  defp prototype_constructor_link(true) do
    quote do
      QuickBEAM.VM.Runtime.InstallerHelpers.install_constructor_link(var!(proto_ref), var!(ctor))
    end
  end

  defp prototype_constructor_link(false), do: nil

  @doc "Sets the current prototype object's parent."
  defmacro object_parent(parent) do
    quote do
      QuickBEAM.VM.Runtime.InstallerHelpers.install_object_parent(
        var!(proto_ref),
        unquote(parent)
      )
    end
  end

  @doc "Sets an internal slot on the current prototype object."
  defmacro internal_slot(key, value) do
    quote do
      QuickBEAM.VM.Heap.put_obj_key(var!(proto_ref), unquote(key), unquote(value))
    end
  end

  @doc "Sets a semantic ECMAScript internal slot on the current prototype object."
  defmacro slot(name, value) do
    quote do
      internal_slot(QuickBEAM.VM.Builtin.slot_key(unquote(name)), unquote(value))
    end
  end

  @doc "Installs a non-enumerable Symbol.toStringTag on the current prototype object."
  defmacro to_string_tag(label) do
    quote do
      QuickBEAM.VM.Runtime.InstallerHelpers.install_to_string_tag(var!(proto_ref), unquote(label))
    end
  end

  @doc "Installs declared properties in the current object context."
  defmacro properties do
    quote do
      QuickBEAM.VM.Builtin.Installer.install_prototype_specs(var!(proto_ref), __MODULE__)
    end
  end

  @doc "Installs declared prototype property specs on the current prototype object."
  defmacro prototype_specs do
    quote do
      properties()
    end
  end

  @doc "Installs the constructor link on the current prototype object."
  defmacro constructor_link do
    quote do
      QuickBEAM.VM.Runtime.InstallerHelpers.install_constructor_link(var!(proto_ref), var!(ctor))
    end
  end

  @doc "Defines prototype methods using contextual `method` entries."
  defmacro prototype(do: block) do
    build_contextual_methods(block, :proto)
  end

  @doc "Defines prototype methods using contextual `method` entries without colliding with local `prototype/1` functions."
  defmacro prototype_methods(do: block) do
    build_contextual_methods(block, :proto)
  end

  @doc "Defines constructor/static methods using contextual `method` entries."
  defmacro statics(do: block) do
    build_contextual_methods(block, :static)
  end

  @doc "Defines constructor/static methods using contextual `method` entries."
  defmacro static_methods(do: block) do
    build_contextual_methods(block, :static)
  end

  @doc "Defines declarative installation metadata for a JavaScript builtin."
  defmacro builtin_definition(name, opts) do
    build_builtin_definition(name, opts, __CALLER__)
  end

  defp build_builtin_definition(name, opts, caller) do
    definition = build_definition_struct(name, opts, caller)

    quote do
      def builtin_definition do
        unquote(definition)
      end

      def builtin_spec do
        QuickBEAM.VM.Builtin.intrinsic_spec(__MODULE__, builtin_definition())
      end

      @ecma nil
      @annex nil
    end
  end

  defp build_definition_struct(name, opts, caller) do
    constructor = Keyword.fetch!(opts, :constructor)
    length = Keyword.get(opts, :length)
    phase = Keyword.get(opts, :phase, :runtime)
    module = Keyword.get(opts, :module, caller.module)
    prototype_parent = Keyword.get(opts, :prototype_parent, :object)
    constructor_descriptor = Keyword.get(opts, :constructor_descriptor, %{})
    prototype_descriptor = Keyword.get(opts, :prototype_descriptor, %{})
    prototype_properties = Keyword.get(opts, :prototype_properties, [])
    constructable? = Keyword.get(opts, :constructable, true)
    intrinsic_key = Keyword.get(opts, :intrinsic_key)
    after_install = Keyword.get(opts, :after_install)
    auto_install? = Keyword.get(opts, :auto_install?, true)

    quote do
      builtin_attrs =
        QuickBEAM.VM.Builtin.opts_with_builtin_attrs(
          unquote(Macro.escape(opts)),
          @ecma,
          @annex
        )

      struct!(QuickBEAM.VM.Builtin.Definition, %{
        name: unquote(name),
        constructor: unquote(constructor),
        length: unquote(length),
        phase: unquote(phase),
        module: unquote(module),
        prototype_parent: unquote(prototype_parent),
        constructor_descriptor:
          Map.merge(
            unquote(Macro.escape(PropertyDescriptor.constructor())),
            unquote(Macro.escape(constructor_descriptor))
          ),
        prototype_descriptor:
          Map.merge(
            unquote(Macro.escape(PropertyDescriptor.prototype())),
            unquote(Macro.escape(prototype_descriptor))
          ),
        prototype_properties: unquote(prototype_properties),
        constructable?: unquote(constructable?),
        intrinsic_key: unquote(intrinsic_key),
        ecma: Keyword.get(builtin_attrs, :ecma),
        annex: Keyword.get(builtin_attrs, :annex),
        after_install: unquote(after_install),
        auto_install?: unquote(auto_install?)
      })
    end
  end

  defp build_contextual_methods(block, target) do
    block
    |> contextual_methods(target)
    |> block_from_entries()
  end

  defp parse_intrinsic_block(block) do
    block
    |> normalize_block()
    |> Enum.reduce({[], []}, fn
      {:install, _, [[do: body]]}, {opts, declarations} ->
        {append_after_install(opts, build_install_callback(body)), declarations}

      {:prototype, _, [prototype_opts, [do: body]]}, {opts, declarations}
      when is_list(prototype_opts) ->
        opts = append_after_install(opts, build_prototype_install_callback(prototype_opts, body))
        declarations = declarations ++ prototype_method_declarations(body)
        {opts, declarations}

      {:install_with, _, [callback]}, {opts, declarations} ->
        {append_after_install(opts, callback), declarations}

      {:phase, _, [phase]}, {opts, declarations} ->
        {Keyword.put(opts, :phase, phase), declarations}

      {:constructor, _, [constructor_opts, [do: body]]}, {opts, declarations}
      when is_list(constructor_opts) ->
        {Keyword.merge(
           opts,
           Keyword.put(constructor_opts, :constructor, build_constructor_callback(body))
         ), declarations}

      {:constructor, _, [[do: body]]}, {opts, declarations} ->
        {Keyword.put(opts, :constructor, build_constructor_callback(body)), declarations}

      {:constructor, _, [callback, constructor_opts]}, {opts, declarations}
      when is_list(constructor_opts) ->
        {Keyword.merge(opts, Keyword.put(constructor_opts, :constructor, callback)), declarations}

      {:constructor, _, [callback]}, {opts, declarations} ->
        {Keyword.put(opts, :constructor, callback), declarations}

      _, acc ->
        acc
    end)
  end

  defp append_after_install(opts, callback) do
    case Keyword.get(opts, :after_install) do
      nil ->
        Keyword.put(opts, :after_install, callback)

      existing ->
        Keyword.put(opts, :after_install, build_install_sequence(existing, callback))
    end
  end

  defp build_install_sequence(first, second) do
    quote do
      fn var!(ctor), var!(opts) ->
        QuickBEAM.VM.Builtin.run_install_callback(unquote(first), var!(ctor), var!(opts))
        QuickBEAM.VM.Builtin.run_install_callback(unquote(second), var!(ctor), var!(opts))
      end
    end
  end

  defp build_constructor_callback(body) do
    quote do
      fn var!(args), var!(this) ->
        _ = var!(args)
        _ = var!(this)
        unquote(body)
      end
    end
  end

  defp build_install_callback(body) do
    quote do
      fn var!(ctor), var!(opts) ->
        _ = var!(ctor)
        _ = var!(opts)
        unquote(body)
      end
    end
  end

  defp build_prototype_install_callback(prototype_opts, body) do
    install_body = prototype_install_body(body)

    quote do
      fn var!(ctor), var!(opts) ->
        _ = var!(ctor)
        _ = var!(opts)

        prototype unquote(Macro.escape(prototype_opts)) do
          unquote(install_body)
        end
      end
    end
  end

  defp prototype_install_body(body) do
    body
    |> normalize_block()
    |> Enum.reject(&prototype_declaration?/1)
    |> block_from_entries()
  end

  defp prototype_method_declarations(body) do
    entries = body |> normalize_block() |> Enum.filter(&prototype_declaration?/1)

    if entries == [] do
      []
    else
      [build_contextual_methods(block_from_entries(entries), :proto)]
    end
  end

  defp prototype_declaration?({:@, _, _}), do: true
  defp prototype_declaration?({:method, _, _}), do: true
  defp prototype_declaration?({:symbol, _, _}), do: true
  defp prototype_declaration?({:accessor, _, _}), do: true
  defp prototype_declaration?({:getter, _, _}), do: true
  defp prototype_declaration?({:property, _, _}), do: true
  defp prototype_declaration?(_entry), do: false

  defmacro symbol(_name, do: _block) do
    raise ArgumentError, "symbol is only available inside builtin object/spec blocks"
  end

  defp contextual_methods(block, target) do
    block
    |> normalize_block()
    |> Enum.map(fn
      {:@, _, _} = attr ->
        attr

      {:method, meta, [name, [do: body]]} ->
        {target, meta, [name, [do: body]]}

      {:method, meta, [name, opts, [do: body]]} ->
        {target, meta, [name, opts, [do: body]]}

      {:symbol, meta, [name, [do: symbol_block]]} ->
        contextual_symbol_entry(target, meta, name, symbol_block)

      {:property, meta, [name, opts]} when is_list(opts) ->
        value = Keyword.fetch!(opts, :value)
        opts = Keyword.delete(opts, :value)
        target_val = if target == :proto, do: :proto_data, else: :static_data
        {target_val, meta, [name, value, opts]}

      {:accessor, meta, [name, [do: block]]} ->
        target_accessor = if target == :proto, do: :proto_accessor, else: :static_accessor
        {target_accessor, meta, [name, [do: block]]}

      {:getter, meta, [name, [do: body]]} ->
        target_getter = if target == :proto, do: :proto_getter, else: :static_getter
        {target_getter, meta, [name, [do: body]]}

      other ->
        other
    end)
  end

  defp contextual_symbol_entry(target, meta, name, block) do
    key = symbol_key(name)

    case normalize_block(block) do
      [{:method, method_meta, [[do: body]]}] ->
        {target, method_meta, [key, [do: body]]}

      [{:method, method_meta, [opts, [do: body]]}] when is_list(opts) ->
        {target, method_meta, [key, opts, [do: body]]}

      entries when is_list(entries) ->
        if Enum.any?(entries, &match?({kind, _, _} when kind in [:get, :set], &1)) do
          target_accessor = if target == :proto, do: :proto_accessor, else: :static_accessor
          {target_accessor, meta, [key, [do: block]]}
        else
          raise ArgumentError, "symbol #{inspect(name)} must declare method/get/set"
        end
    end
  end

  defp symbol_key({:symbol, _} = key), do: key
  defp symbol_key(name) when is_atom(name), do: {:symbol, "Symbol.#{name}"}
  defp symbol_key("Symbol." <> _ = name), do: {:symbol, name}
  defp symbol_key(name) when is_binary(name), do: {:symbol, "Symbol.#{name}"}

  defp block_from_entries([]), do: :ok
  defp block_from_entries([entry]), do: entry
  defp block_from_entries(entries), do: {:__block__, [], entries}

  # ── Named object macro ──

  @doc "Defines a named builtin object exported by `object/0`."
  defmacro js_object(name, do: block) do
    map_entries = build_map_entries(normalize_block(block))

    quote do
      def object do
        {:builtin, unquote(name), %{unquote_splicing(map_entries)}}
      end
    end
  end

  # ── Inline map/list macros ──

  @doc "Builds a raw map of builtin method/property entries."
  defmacro build_methods(do: block) do
    map_entries = build_map_entries(normalize_block(block))
    quote do: %{unquote_splicing(map_entries)}
  end

  defmacro object(opts \\ [], do: block) do
    map_entries = build_map_entries(normalize_block(block))
    heap? = Keyword.get(opts, :heap, true)

    if heap? do
      quote do
        QuickBEAM.VM.Heap.wrap(%{unquote_splicing(map_entries)})
      end
    else
      quote do: %{unquote_splicing(map_entries)}
    end
  end

  @doc "Builds a heap-wrapped object from builtin method/property entries."
  defmacro build_object(do: block) do
    map_entries = build_map_entries(normalize_block(block))

    quote do
      QuickBEAM.VM.Heap.wrap(%{unquote_splicing(map_entries)})
    end
  end

  @doc "Registers a JavaScript constructor and optional prototype definition."
  defmacro constructor(name, callback) do
    build_constructor(name, callback, [], nil)
  end

  defmacro constructor(name, callback, do: block) do
    {proto_entries, parent} = parse_constructor_block(block)
    build_constructor(name, callback, proto_entries, parent)
  end

  # ── Shared builders ──

  defp build_constructor(name, callback, proto_entries, parent) do
    proto_map_entries = build_map_entries(proto_entries)

    quote do
      QuickBEAM.VM.Runtime.ConstructorRegistry.register(
        unquote(name),
        unquote(callback),
        %{unquote_splicing(proto_map_entries)},
        unquote(parent)
      )
    end
  end

  defp build_builtin(name, body, opts) do
    callback_body = build_callback_body(body, Keyword.get(opts, :receiver))

    quote do
      QuickBEAM.VM.Builtin.builtin(
        unquote(builtin_property_name(name)),
        fn var!(args), var!(this) ->
          _ = var!(args)
          unquote(callback_body)
        end,
        unquote(Macro.escape(opts))
      )
    end
  end

  defp build_callback_body(body, nil) do
    quote do
      _ = var!(this)
      unquote(body)
    end
  end

  defp build_callback_body(body, receiver) do
    quote do
      var!(this) = QuickBEAM.VM.Builtin.require_receiver!(unquote(receiver), var!(this))
      unquote(body)
    end
  end

  defp normalize_block({:__block__, _, entries}), do: entries
  defp normalize_block(single), do: [single]

  defp build_map_entries(entries) do
    {map_entries, _pending_opts} =
      Enum.reduce(entries, {[], []}, fn
        {:@, _, [{:ecma, _, [ecma]}]}, {built, pending_opts} ->
          {built, Keyword.put(pending_opts, :ecma, ecma)}

        {:@, _, [{:annex, _, [annex]}]}, {built, pending_opts} ->
          {built, Keyword.put(pending_opts, :annex, annex)}

        {:@, _, [{:doc, _, [_doc]}]}, {built, pending_opts} ->
          {built, pending_opts}

        entry, {built, pending_opts} ->
          {[build_map_entry(entry, pending_opts) | built], []}
      end)

    Enum.reverse(map_entries)
  end

  defp parse_constructor_block(block) do
    block
    |> normalize_block()
    |> Enum.reduce({[], nil}, fn
      {:proto, _, [[do: proto_block]]}, {_entries, _parent} ->
        parse_proto_block(proto_block)

      entry, {entries, parent} ->
        {[entry | entries], parent}
    end)
    |> then(fn {entries, parent} -> {Enum.reverse(entries), parent} end)
  end

  defp parse_proto_block(block) do
    block
    |> normalize_block()
    |> Enum.reduce({[], nil}, fn
      {:extends, _, [parent]}, {entries, _parent} -> {entries, parent}
      entry, {entries, parent} -> {[entry | entries], parent}
    end)
    |> then(fn {entries, parent} -> {Enum.reverse(entries), parent} end)
  end

  defp build_map_entry(entry, pending_opts)

  defp build_map_entry({:method, _, [name, [do: body]]}, pending_opts) do
    {name, build_builtin(name, body, pending_opts)}
  end

  defp build_map_entry({:method, _, [name, opts, [do: body]]}, pending_opts) when is_list(opts) do
    {name, build_builtin(name, body, Keyword.merge(pending_opts, opts))}
  end

  defp build_map_entry({:args_method, _, [name, callback]}, _pending_opts) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_args(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:receiver_method, _, [name, callback]}, _pending_opts) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_receiver(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:this_method, _, [name, callback]}, _pending_opts) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_this(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:symbol, _, [name, [do: block]]}, pending_opts) do
    key = symbol_key(name)

    case normalize_block(block) do
      [{:method, _, [[do: body]]}] ->
        {key, build_builtin(key, body, pending_opts)}

      [{:method, _, [opts, [do: body]]}] when is_list(opts) ->
        {key, build_builtin(key, body, Keyword.merge(pending_opts, opts))}

      entries when is_list(entries) ->
        if Enum.any?(entries, &match?({kind, _, _} when kind in [:get, :set], &1)) do
          {getter, setter} = build_accessor_parts(key, block, pending_opts)
          {key, quote(do: {:accessor, unquote(getter), unquote(setter)})}
        else
          raise ArgumentError, "symbol #{inspect(name)} must declare method/get/set"
        end
    end
  end

  defp build_map_entry({:accessor, _, [name, [do: block]]}, pending_opts) do
    {getter, setter} = build_accessor_parts(name, block, pending_opts)
    {name, quote(do: {:accessor, unquote(getter), unquote(setter)})}
  end

  defp build_map_entry({:getter, _, [name, [do: body]]}, pending_opts) do
    {name, quote(do: {:accessor, unquote(build_builtin("get #{name}", body, pending_opts)), nil})}
  end

  defp build_map_entry({:property, _, [name, opts]}, _pending_opts) when is_list(opts) do
    {name, Keyword.fetch!(opts, :value)}
  end

  defp build_map_entry({:val, _, [name, value]}, _pending_opts) do
    {name, value}
  end

  defp build_map_entry({:prop, _, [name, value]}, _pending_opts) do
    {name, value}
  end

  defp build_accessor_parts(name, block, pending_opts) do
    block
    |> normalize_block()
    |> Enum.reduce({nil, nil}, fn
      {:get, _, [[do: body]]}, {_getter, setter} ->
        {build_builtin("get #{builtin_property_name(name)}", body, pending_opts), setter}

      {:set, _, [[do: body]]}, {getter, _setter} ->
        {getter, build_builtin("set #{builtin_property_name(name)}", body, pending_opts)}
    end)
  end

  defp builtin_property_name({:symbol, name}), do: "[#{name}]"
  defp builtin_property_name(name) when is_binary(name), do: name
  defp builtin_property_name(name), do: inspect(name)

  # ── Runtime helpers ──

  @doc "Returns a positional argument with a JavaScript `:undefined` default."
  def arg(args, index, default \\ :undefined), do: Enum.at(args, index, default)

  def argv(args, defaults) do
    defaults
    |> Enum.with_index()
    |> Enum.map(fn {default, index} -> arg(args, index, default) end)
  end

  @doc "Wraps a two-arity callback in the VM builtin tuple representation."
  def builtin(name, callback, opts \\ [])

  def builtin(name, callback, %Meta{} = meta) when is_function(callback, 2) do
    {:builtin, name, callback}
    |> put_builtin_metadata(meta)
  end

  def builtin(name, callback, opts) when is_function(callback, 2) do
    function = {:builtin, name, callback}

    case opts do
      [] -> function
      _ -> put_builtin_metadata(function, meta(name, opts))
    end
  end

  def builtin_args(name, callback) when is_function(callback, 1) do
    {:builtin, name, fn args, _this -> callback.(args) end}
  end

  def builtin_receiver(name, callback) when is_function(callback, 2) do
    {:builtin, name, fn args, this -> callback.(this, args) end}
  end

  @doc "Wraps a receiver-only callback in the VM builtin tuple representation."
  def builtin_this(name, callback) when is_function(callback, 1) do
    {:builtin, name, fn _args, this -> callback.(this) end}
  end

  def put_if_present(map, _key, nil), do: map
  def put_if_present(map, key, value), do: Map.put(map, key, value)

  @doc "Runs an intrinsic install callback with either supported callback arity."
  def run_install_callback(callback, ctor, opts) when is_function(callback, 2),
    do: callback.(ctor, opts)

  def run_install_callback(callback, ctor, _opts) when is_function(callback, 1),
    do: callback.(ctor)

  @doc "Maps semantic ECMAScript internal slot names to heap storage keys."
  def slot_key(:BooleanData), do: QuickBEAM.VM.ObjectModel.WrappedPrimitive.slot(:boolean)
  def slot_key(:NumberData), do: QuickBEAM.VM.ObjectModel.WrappedPrimitive.slot(:number)
  def slot_key(:StringData), do: QuickBEAM.VM.ObjectModel.WrappedPrimitive.slot(:string)
  def slot_key(:BigIntData), do: QuickBEAM.VM.ObjectModel.WrappedPrimitive.slot(:bigint)
  def slot_key(:SymbolData), do: QuickBEAM.VM.ObjectModel.WrappedPrimitive.slot(:symbol)
  def slot_key(key), do: key

  @doc "Validates and unwraps a builtin method receiver according to a DSL contract."
  def require_receiver!(nil, this), do: this
  def require_receiver!(:boolean, this), do: require_wrapped_primitive!(this, :boolean, "Boolean")
  def require_receiver!(:number, this), do: require_wrapped_primitive!(this, :number, "Number")
  def require_receiver!(:string, this), do: require_wrapped_primitive!(this, :string, "String")
  def require_receiver!(:bigint, this), do: require_bigint_receiver!(this)
  def require_receiver!(:symbol, this), do: require_symbol_receiver!(this)

  defp require_wrapped_primitive!({:obj, ref}, kind, label) do
    case QuickBEAM.VM.Heap.get_obj(ref, %{})
         |> QuickBEAM.VM.ObjectModel.WrappedPrimitive.value(kind) do
      {:ok, value} ->
        value

      :error ->
        QuickBEAM.VM.JSThrow.type_error!("#{label} method called on incompatible receiver")
    end
  end

  defp require_wrapped_primitive!(value, :boolean, _label) when is_boolean(value), do: value

  defp require_wrapped_primitive!(value, :number, _label)
       when is_number(value) or value in [:nan, :infinity, :neg_infinity],
       do: value

  defp require_wrapped_primitive!(value, :string, _label) when is_binary(value), do: value

  defp require_wrapped_primitive!(_value, _kind, label),
    do: QuickBEAM.VM.JSThrow.type_error!("#{label} method called on incompatible receiver")

  defp require_bigint_receiver!({:bigint, _} = value), do: value

  defp require_bigint_receiver!({:obj, ref}) do
    case QuickBEAM.VM.Heap.get_obj(ref, %{})
         |> QuickBEAM.VM.ObjectModel.WrappedPrimitive.value(:bigint) do
      {:ok, {:bigint, _} = value} -> value
      {:ok, value} when is_integer(value) -> {:bigint, value}
      :error -> QuickBEAM.VM.JSThrow.type_error!("BigInt method called on incompatible receiver")
    end
  end

  defp require_bigint_receiver!(_value),
    do: QuickBEAM.VM.JSThrow.type_error!("BigInt method called on incompatible receiver")

  defp require_symbol_receiver!({:symbol, _} = value), do: value
  defp require_symbol_receiver!({:symbol, _, _} = value), do: value

  defp require_symbol_receiver!({:obj, ref}) do
    case QuickBEAM.VM.Heap.get_obj(ref, %{})
         |> QuickBEAM.VM.ObjectModel.WrappedPrimitive.value(:symbol) do
      {:ok, value} ->
        value

      :error ->
        QuickBEAM.VM.JSThrow.type_error!(
          "Symbol.prototype method called on incompatible receiver"
        )
    end
  end

  defp require_symbol_receiver!(_value),
    do:
      QuickBEAM.VM.JSThrow.type_error!("Symbol.prototype method called on incompatible receiver")

  def iterator_from(items) do
    iter = QuickBEAM.VM.Heap.wrap_iterator(items)

    with {:obj, ref} <- iter do
      QuickBEAM.VM.Heap.update_obj(ref, %{}, fn map ->
        Map.put(
          map,
          {:symbol, "Symbol.iterator"},
          builtin("[Symbol.iterator]", fn _, this -> this end)
        )
      end)
    end

    iter
  end

  # ── Runtime dispatch ──

  import QuickBEAM.VM.Heap.Keys, only: [proxy_target: 0]
  alias QuickBEAM.VM.{Heap, JSThrow}

  @doc "Dispatches a VM callable value to its underlying Elixir callback."
  def call({:builtin, name, _cb}, _args, _this)
      when name in ~w(Map Set WeakMap WeakSet WeakRef FinalizationRegistry DataView Promise) do
    JSThrow.type_error!("Constructor #{name} requires 'new'")
  end

  def call({:builtin, _, cb}, args, this) when is_function(cb, 2), do: cb.(args, this)

  def call({:bound, _, inner, _, _}, args, this), do: call(inner, args, this)

  def call({:obj, _} = obj, _args, _this) do
    if obj == Heap.get_func_proto(), do: :undefined, else: JSThrow.type_error!("not a function")
  end

  def call(f, args, _this) when is_function(f, 2), do: f.(args, nil)

  def call(f, args, _this) when is_function(f, 1), do: f.(args)

  def call(f, args, _this) when is_function(f), do: apply(f, args)

  def call(_, _, _),
    do: JSThrow.type_error!("not a function")

  @doc "Returns a built-in function's JavaScript name, if present."
  def name({:builtin, name, _}), do: name
  def name(_), do: nil

  @doc "Returns whether a VM value can be called as a JavaScript function."
  def callable?(%QuickBEAM.VM.Function{}), do: true

  def callable?({:closure, _, %QuickBEAM.VM.Function{}}), do: true

  def callable?({:builtin, _, callback}) when is_function(callback), do: true
  def callable?({:builtin, _, _}), do: false

  def callable?({:bound, _, _, _, _}), do: true

  def callable?({:obj, ref} = obj) do
    obj == Heap.get_func_proto() or
      case Heap.get_obj(ref, %{}) do
        %{proxy_target() => target} -> callable?(target)
        _ -> false
      end
  end

  def callable?(f) when is_function(f), do: true

  def callable?(_), do: false
end
