defmodule QuickBEAM.VM.Builtin do
  @moduledoc "Macros and helpers for defining JS builtins."

  @doc """
  Uniform macros for defining JS builtins in all contexts.

  All builtins use 2-arity `fn args, this ->` convention.

  ## Module-level dispatch (generates def clauses)

      proto "push" do ... end         # → def proto_property("push")
      static "isArray" do ... end     # → def static_property("isArray")
      static_val "PI", :math.pi()    # → def static_property("PI"), do: value

  ## Named object (generates def object/0)

      js_object "Math" do
        method "floor" do ... end
        val "PI", :math.pi()
      end

  ## Inline maps and objects

      build_methods do              # returns %{"name" => {:builtin, ...}, ...}
        method "add" do ... end
        args_method "from", &from_args/1
        receiver_method "slice", &slice/2
        this_method "toJSON", &to_json/1
        symbol_method "Symbol.iterator" do ... end
        accessor "size" do
          get do ... end
        end
        prop "size", 0
      end

      object do                     # returns Heap.wrap(%{"name" => {:builtin, ...}, ...})
        prop "type", type
        method "preventDefault" do ... end
      end

      object heap: false do         # returns the raw map for post-processing
        prop "searchParams", search_params
      end

      constructor "DOMException", &build_dom_exception/2 do
        proto do
          extends build_error_proto()
        end
      end

  `args` and `this` are injected in all `proto`/`static`/`method` bodies.
  `arg/3`, `argv/2`, `builtin_*`, and `iterator_from/1` cover the repeated
  argument-defaulting, function-wrapping, and iterator boilerplate used by Web APIs.
  Catch-all fallbacks are auto-generated by @before_compile.
  """

  defmacro __using__(_opts) do
    quote do
      @behaviour QuickBEAM.VM.Runtime.BuiltinObject

      import QuickBEAM.VM.Builtin,
        only: [
          proto: 2,
          static: 2,
          static_val: 2,
          js_object: 2,
          build_methods: 1,
          build_object: 1,
          object: 1,
          object: 2,
          constructor: 2,
          constructor: 3,
          arg: 2,
          arg: 3,
          argv: 2,
          builtin: 2,
          builtin_args: 2,
          builtin_receiver: 2,
          builtin_this: 2,
          iterator_from: 1
        ]

      Module.register_attribute(__MODULE__, :__has_proto, accumulate: false)
      Module.register_attribute(__MODULE__, :__has_static, accumulate: false)
      @before_compile QuickBEAM.VM.Builtin
    end
  end

  @doc "Emits fallback clauses for modules that define prototype or static properties."
  defmacro __before_compile__(env) do
    has_proto = Module.get_attribute(env.module, :__has_proto)
    has_static = Module.get_attribute(env.module, :__has_static)

    proto_fallback =
      if has_proto do
        quote do: def(proto_property(_), do: :undefined)
      end

    static_fallback =
      if has_static do
        quote do: def(static_property(_), do: :undefined)
      end

    [proto_fallback, static_fallback]
    |> Enum.reject(&is_nil/1)
    |> case do
      [] -> nil
      blocks -> {:__block__, [], blocks}
    end
  end

  # ── Module-level dispatch macros ──

  @doc "Defines a prototype property as a JavaScript builtin function."
  defmacro proto(name, do: body) do
    quote do
      @__has_proto true
      def proto_property(unquote(name)) do
        unquote(build_builtin(name, body))
      end
    end
  end

  @doc "Defines a constructor/static property as a JavaScript builtin function."
  defmacro static(name, do: body) do
    quote do
      @__has_static true
      def static_property(unquote(name)) do
        unquote(build_builtin(name, body))
      end
    end
  end

  @doc "Defines a constructor/static property as a fixed value."
  defmacro static_val(name, value) do
    quote do
      @__has_static true
      def static_property(unquote(name)), do: unquote(value)
    end
  end

  # ── Named object macro ──

  @doc "Defines a named builtin object exported by `object/0`."
  defmacro js_object(name, do: block) do
    entries = normalize_block(block)
    map_entries = Enum.map(entries, &build_map_entry/1)

    quote do
      def object do
        {:builtin, unquote(name), %{unquote_splicing(map_entries)}}
      end
    end
  end

  # ── Inline map/list macros ──

  @doc "Builds a raw map of builtin method/property entries."
  defmacro build_methods(do: block) do
    entries = normalize_block(block)
    map_entries = Enum.map(entries, &build_map_entry/1)
    quote do: %{unquote_splicing(map_entries)}
  end

  defmacro object(opts \\ [], do: block) do
    entries = normalize_block(block)
    map_entries = Enum.map(entries, &build_map_entry/1)
    heap? = Keyword.get(opts, :heap, true)

    if heap? do
      quote do
        QuickBEAM.VM.Heap.wrap(%{unquote_splicing(map_entries)})
      end
    else
      quote do: %{unquote_splicing(map_entries)}
    end
  end

  @doc "Builds a heap-wrapped object from builtin method/property entries."
  defmacro build_object(do: block) do
    entries = normalize_block(block)
    map_entries = Enum.map(entries, &build_map_entry/1)

    quote do
      QuickBEAM.VM.Heap.wrap(%{unquote_splicing(map_entries)})
    end
  end

  @doc "Registers a JavaScript constructor and optional prototype definition."
  defmacro constructor(name, callback) do
    build_constructor(name, callback, [], nil)
  end

  defmacro constructor(name, callback, do: block) do
    {proto_entries, parent} = parse_constructor_block(block)
    build_constructor(name, callback, proto_entries, parent)
  end

  # ── Shared builders ──

  defp build_constructor(name, callback, proto_entries, parent) do
    proto_map_entries = Enum.map(proto_entries, &build_map_entry/1)

    quote do
      QuickBEAM.VM.Runtime.Constructors.register(
        unquote(name),
        unquote(callback),
        %{unquote_splicing(proto_map_entries)},
        unquote(parent)
      )
    end
  end

  defp build_builtin(name, body) do
    quote do
      {:builtin, unquote(name),
       fn var!(args), var!(this) ->
         _ = var!(args)
         _ = var!(this)
         unquote(body)
       end}
    end
  end

  defp normalize_block({:__block__, _, entries}), do: entries
  defp normalize_block(single), do: [single]

  defp parse_constructor_block(block) do
    block
    |> normalize_block()
    |> Enum.reduce({[], nil}, fn
      {:proto, _, [[do: proto_block]]}, {_entries, _parent} ->
        parse_proto_block(proto_block)

      entry, {entries, parent} ->
        {[entry | entries], parent}
    end)
    |> then(fn {entries, parent} -> {Enum.reverse(entries), parent} end)
  end

  defp parse_proto_block(block) do
    block
    |> normalize_block()
    |> Enum.reduce({[], nil}, fn
      {:extends, _, [parent]}, {entries, _parent} -> {entries, parent}
      entry, {entries, parent} -> {[entry | entries], parent}
    end)
    |> then(fn {entries, parent} -> {Enum.reverse(entries), parent} end)
  end

  defp build_map_entry({:method, _, [name, [do: body]]}) do
    {name, build_builtin(name, body)}
  end

  defp build_map_entry({:args_method, _, [name, callback]}) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_args(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:receiver_method, _, [name, callback]}) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_receiver(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:this_method, _, [name, callback]}) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_this(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:symbol_method, _, [name, [do: body]]}) do
    {{:symbol, name}, build_builtin("[#{name}]", body)}
  end

  defp build_map_entry({:accessor, _, [name, [do: block]]}) do
    {getter, setter} = build_accessor_parts(name, block)
    {name, quote(do: {:accessor, unquote(getter), unquote(setter)})}
  end

  defp build_map_entry({:getter, _, [name, [do: body]]}) do
    {name, quote(do: {:accessor, unquote(build_builtin("get #{name}", body)), nil})}
  end

  defp build_map_entry({:val, _, [name, value]}) do
    {name, value}
  end

  defp build_map_entry({:prop, _, [name, value]}) do
    {name, value}
  end

  defp build_accessor_parts(name, block) do
    block
    |> normalize_block()
    |> Enum.reduce({nil, nil}, fn
      {:get, _, [[do: body]]}, {_getter, setter} -> {build_builtin("get #{name}", body), setter}
      {:set, _, [[do: body]]}, {getter, _setter} -> {getter, build_builtin("set #{name}", body)}
    end)
  end

  # ── Runtime helpers ──

  @doc "Returns a positional argument with a JavaScript `:undefined` default."
  def arg(args, index, default \\ :undefined), do: Enum.at(args, index, default)

  def argv(args, defaults) do
    defaults
    |> Enum.with_index()
    |> Enum.map(fn {default, index} -> arg(args, index, default) end)
  end

  @doc "Wraps a two-arity callback in the VM builtin tuple representation."
  def builtin(name, callback) when is_function(callback, 2), do: {:builtin, name, callback}

  def builtin_args(name, callback) when is_function(callback, 1) do
    {:builtin, name, fn args, _this -> callback.(args) end}
  end

  def builtin_receiver(name, callback) when is_function(callback, 2) do
    {:builtin, name, fn args, this -> callback.(this, args) end}
  end

  @doc "Wraps a receiver-only callback in the VM builtin tuple representation."
  def builtin_this(name, callback) when is_function(callback, 1) do
    {:builtin, name, fn _args, this -> callback.(this) end}
  end

  def put_if_present(map, _key, nil), do: map
  def put_if_present(map, key, value), do: Map.put(map, key, value)

  def iterator_from(items) do
    iter = QuickBEAM.VM.Heap.wrap_iterator(items)

    with {:obj, ref} <- iter do
      QuickBEAM.VM.Heap.update_obj(ref, %{}, fn map ->
        Map.put(
          map,
          {:symbol, "Symbol.iterator"},
          builtin("[Symbol.iterator]", fn _, this -> this end)
        )
      end)
    end

    iter
  end

  # ── Runtime dispatch ──

  alias QuickBEAM.VM.JSThrow

  @doc "Dispatches a VM callable value to its underlying Elixir callback."
  def call({:builtin, _, cb}, args, this), do: cb.(args, this)

  def call({:bound, _, inner, _, _}, args, this), do: call(inner, args, this)

  def call(f, args, _this) when is_function(f, 2), do: f.(args, nil)

  def call(f, args, _this) when is_function(f, 1), do: f.(args)

  def call(f, args, _this) when is_function(f), do: apply(f, args)

  def call(_, _, _),
    do: JSThrow.type_error!("not a function")

  @doc "Returns whether a VM value can be called as a JavaScript function."
  def callable?(%QuickBEAM.VM.Function{}), do: true

  def callable?({:closure, _, %QuickBEAM.VM.Function{}}), do: true

  def callable?({:builtin, _, _}), do: true

  def callable?({:bound, _, _, _, _}), do: true

  def callable?(f) when is_function(f), do: true

  def callable?(_), do: false
end
