defmodule QuickBEAM.VM.Builtin do
  @moduledoc """
  Macros and helpers for defining JS builtins in all contexts.

  All builtins use 2-arity `fn args, this ->` convention.

  ## Module-level dispatch (generates def clauses)

      proto "push" do ... end         # → def proto_property("push")
      static "isArray" do ... end     # → def static_property("isArray")
      static_val "PI", :math.pi()    # → def static_property("PI"), do: value

  ## Named object (generates def object/0)

      js_object "Math" do
        method "floor" do ... end
        val "PI", :math.pi()
      end

  ## Inline maps and objects

      build_methods do              # returns %{"name" => {:builtin, ...}, ...}
        method "add" do ... end
        args_method "from", &from_args/1
        receiver_method "slice", &slice/2
        this_method "toJSON", &to_json/1
        symbol_method "Symbol.iterator" do ... end
        accessor "size" do
          get do ... end
        end
        prop "size", 0
      end

      object do                     # returns Heap.wrap(%{"name" => {:builtin, ...}, ...})
        prop "type", type
        method "preventDefault" do ... end
      end

      object heap: false do         # returns the raw map for post-processing
        prop "searchParams", search_params
      end

      constructor "DOMException", &build_dom_exception/2 do
        proto do
          extends build_error_proto()
        end
      end

  `args` and `this` are injected in all `proto`/`static`/`method` bodies.
  `arg/3`, `argv/2`, `builtin_*`, and `iterator_from/1` cover the repeated
  argument-defaulting, function-wrapping, and iterator boilerplate used by Web APIs.
  Catch-all fallbacks are auto-generated by @before_compile.
  """

  alias QuickBEAM.VM.Heap
  alias QuickBEAM.VM.ObjectModel.PropertyDescriptor

  defmodule FunctionSpec do
    @moduledoc "Declarative metadata for an ECMAScript builtin function."

    defstruct name: nil,
              length: 0,
              kind: :function,
              constructable?: false,
              writable?: true,
              enumerable?: false,
              configurable?: true,
              ecma: nil,
              annex: nil
  end

  defmodule PropertySpec do
    @moduledoc "Declarative metadata for an ECMAScript builtin property."

    defstruct key: nil,
              kind: :data,
              value: nil,
              descriptor: %{},
              ecma: nil,
              annex: nil
  end

  defmodule ObjectSpec do
    @moduledoc "Declarative metadata for an ECMAScript builtin object."

    defstruct name: nil,
              intrinsic: nil,
              properties: [],
              prototype: nil,
              ecma: nil,
              annex: nil
  end

  defmodule IntrinsicSpec do
    @moduledoc "Declarative metadata for an ECMAScript intrinsic graph entry."

    defstruct name: nil,
              constructor: nil,
              statics: [],
              prototype: nil,
              ecma: nil,
              annex: nil
  end

  defmodule Meta do
    @moduledoc "Metadata attached to JavaScript builtin functions and properties."

    defstruct name: nil,
              length: 0,
              constructable?: false,
              writable?: true,
              enumerable?: false,
              configurable?: true,
              kind: :function,
              ecma: nil,
              annex: nil
  end

  @doc "Builds builtin metadata from macro options."
  def meta(name, opts \\ [], kind \\ :function) do
    name
    |> function_spec(opts, kind)
    |> function_meta()
  end

  def function_meta(%FunctionSpec{} = spec) do
    %Meta{
      name: spec.name,
      length: spec.length,
      constructable?: spec.constructable?,
      writable?: spec.writable?,
      enumerable?: spec.enumerable?,
      configurable?: spec.configurable?,
      kind: spec.kind,
      ecma: spec.ecma,
      annex: spec.annex
    }
  end

  @doc "Builds a first-class function spec from builtin macro options."
  def function_spec(name, opts \\ [], kind \\ :function) do
    %FunctionSpec{
      name: Keyword.get(opts, :name, name),
      length: Keyword.get(opts, :length, 0),
      constructable?: Keyword.get(opts, :constructable, false),
      writable?: Keyword.get(opts, :writable, true),
      enumerable?: Keyword.get(opts, :enumerable, false),
      configurable?: Keyword.get(opts, :configurable, true),
      kind: kind,
      ecma: Keyword.get(opts, :ecma),
      annex: Keyword.get(opts, :annex)
    }
  end

  @doc "Returns metadata for a module-level static builtin, when the module declares it."
  def static_meta(module, name) when is_atom(module) do
    if function_exported?(module, :static_property_meta, 1), do: module.static_property_meta(name)
  end

  @doc "Returns metadata for a module-level prototype builtin, when the module declares it."
  def proto_meta(module, name) when is_atom(module) do
    if function_exported?(module, :proto_property_meta, 1), do: module.proto_property_meta(name)
  end

  @doc "Returns whether builtin metadata marks a value as constructable."
  def constructable?(%Meta{constructable?: constructable?}), do: constructable?
  def constructable?(_), do: false

  @doc "Returns the declared length from builtin metadata or zero."
  def length(%Meta{length: length}), do: length
  def length(_), do: 0

  @doc "Returns metadata attached to a builtin function, falling back to legacy name metadata."
  def metadata_for({:builtin, name, _} = builtin) do
    Map.get(Heap.get_ctor_statics(builtin), :__builtin_meta__) || named_meta(name)
  end

  def metadata_for(name) when is_binary(name), do: named_meta(name)
  def metadata_for(_), do: nil

  @doc "Returns the declared builtin length or the supplied default."
  def declared_length(value, default \\ :undefined) do
    case metadata_for(value) do
      %Meta{length: length} -> length
      _ -> default
    end
  end

  @doc "Stores internal builtin metadata on a callable or constructor."
  def put_builtin_metadata(function, %Meta{} = meta) do
    Heap.put_ctor_static(function, :__builtin_meta__, meta)
    function
  end

  @doc "Stores JavaScript-visible function name and length metadata."
  def put_function_metadata(function, name, length) do
    Heap.put_ctor_static(function, "length", length)
    Heap.put_ctor_static(function, "name", name)
    function
  end

  @doc "Returns built-in function metadata by JavaScript-visible function name."
  def named_meta("Object"), do: meta("Object", [length: 1, constructable: true], :constructor)
  def named_meta("Function"), do: meta("Function", [length: 1, constructable: true], :constructor)
  def named_meta("String"), do: meta("String", [length: 1, constructable: true], :constructor)
  def named_meta("Number"), do: meta("Number", [length: 1, constructable: true], :constructor)
  def named_meta("Array"), do: meta("Array", [length: 1, constructable: true], :constructor)
  def named_meta("Boolean"), do: meta("Boolean", [length: 1, constructable: true], :constructor)
  def named_meta("RegExp"), do: meta("RegExp", [length: 2, constructable: true], :constructor)
  def named_meta("Date"), do: meta("Date", [length: 7, constructable: true], :constructor)
  def named_meta("Promise"), do: meta("Promise", [length: 1, constructable: true], :constructor)

  def named_meta("ArrayBuffer"),
    do: meta("ArrayBuffer", [length: 1, constructable: true], :constructor)

  def named_meta("SharedArrayBuffer"),
    do: meta("SharedArrayBuffer", [length: 1, constructable: true], :constructor)

  def named_meta("DataView"), do: meta("DataView", [length: 1, constructable: true], :constructor)
  def named_meta("Error"), do: meta("Error", [length: 1, constructable: true], :constructor)

  def named_meta("AggregateError"),
    do: meta("AggregateError", [length: 2, constructable: true], :constructor)

  def named_meta("SuppressedError"),
    do: meta("SuppressedError", [length: 3, constructable: true], :constructor)

  def named_meta("EvalError"),
    do: meta("EvalError", [length: 1, constructable: true], :constructor)

  def named_meta("RangeError"),
    do: meta("RangeError", [length: 1, constructable: true], :constructor)

  def named_meta("ReferenceError"),
    do: meta("ReferenceError", [length: 1, constructable: true], :constructor)

  def named_meta("SyntaxError"),
    do: meta("SyntaxError", [length: 1, constructable: true], :constructor)

  def named_meta("TypeError"),
    do: meta("TypeError", [length: 1, constructable: true], :constructor)

  def named_meta("URIError"), do: meta("URIError", [length: 1, constructable: true], :constructor)
  def named_meta("Map"), do: meta("Map", [length: 0, constructable: true], :constructor)
  def named_meta("Set"), do: meta("Set", [length: 0, constructable: true], :constructor)
  def named_meta("WeakMap"), do: meta("WeakMap", [length: 0, constructable: true], :constructor)
  def named_meta("WeakSet"), do: meta("WeakSet", [length: 0, constructable: true], :constructor)
  def named_meta("WeakRef"), do: meta("WeakRef", [length: 1, constructable: true], :constructor)

  def named_meta("FinalizationRegistry"),
    do: meta("FinalizationRegistry", [length: 1, constructable: true], :constructor)

  def named_meta("assign"), do: meta("assign", [length: 2, constructable: false], :static)
  def named_meta("create"), do: meta("create", [length: 2, constructable: false], :static)

  def named_meta("defineProperty"),
    do: meta("defineProperty", [length: 3, constructable: false], :static)

  def named_meta("defineProperties"),
    do: meta("defineProperties", [length: 2, constructable: false], :static)

  def named_meta("getOwnPropertyDescriptor"),
    do: meta("getOwnPropertyDescriptor", [length: 2, constructable: false], :static)

  def named_meta(name)
      when name in [
             "getOwnPropertyDescriptors",
             "getOwnPropertyNames",
             "getOwnPropertySymbols",
             "getPrototypeOf"
           ],
      do: meta(name, [length: 1, constructable: false], :static)

  def named_meta("hasOwn"), do: meta("hasOwn", [length: 2, constructable: false], :static)
  def named_meta("groupBy"), do: meta("groupBy", [length: 2, constructable: false], :static)
  def named_meta("is"), do: meta("is", [length: 2, constructable: false], :static)

  def named_meta("parse"), do: meta("parse", [length: 2, constructable: false], :static)
  def named_meta("stringify"), do: meta("stringify", [length: 3, constructable: false], :static)
  def named_meta("rawJSON"), do: meta("rawJSON", [length: 1, constructable: false], :static)
  def named_meta("isRawJSON"), do: meta("isRawJSON", [length: 1, constructable: false], :static)

  def named_meta(name)
      when name in [
             "abs",
             "acos",
             "acosh",
             "asin",
             "asinh",
             "atan",
             "atan2",
             "atanh",
             "cbrt",
             "ceil",
             "clz32",
             "cos",
             "cosh",
             "exp",
             "expm1",
             "floor",
             "f16round",
             "fround",
             "hypot",
             "imul",
             "log",
             "log10",
             "log1p",
             "log2",
             "max",
             "min",
             "pow",
             "random",
             "round",
             "sign",
             "sin",
             "sinh",
             "sqrt",
             "sumPrecise",
             "tan",
             "tanh",
             "trunc"
           ],
      do:
        meta(
          name,
          [
            length:
              cond do
                name in ["atan2", "hypot", "imul", "max", "min", "pow"] -> 2
                name == "random" -> 0
                true -> 1
              end,
            constructable: false
          ],
          :static
        )

  def named_meta("getOwnPropertyDescriptor"),
    do: meta("getOwnPropertyDescriptor", [length: 2, constructable: false], :static)

  def named_meta("getOwnPropertyNames"),
    do: meta("getOwnPropertyNames", [length: 1, constructable: false], :static)

  def named_meta("getOwnPropertyDescriptors"),
    do: meta("getOwnPropertyDescriptors", [length: 1, constructable: false], :static)

  def named_meta("getPrototypeOf"),
    do: meta("getPrototypeOf", [length: 1, constructable: false], :static)

  def named_meta("construct"), do: meta("construct", [length: 2, constructable: false], :static)

  def named_meta("deleteProperty"),
    do: meta("deleteProperty", [length: 2, constructable: false], :static)

  def named_meta("ownKeys"), do: meta("ownKeys", [length: 1, constructable: false], :static)

  def named_meta("setPrototypeOf"),
    do: meta("setPrototypeOf", [length: 2, constructable: false], :static)

  def named_meta("keys"), do: meta("keys", [length: 1, constructable: false], :static)
  def named_meta("values"), do: meta("values", [length: 1, constructable: false], :static)
  def named_meta("entries"), do: meta("entries", [length: 1, constructable: false], :static)
  def named_meta("escape"), do: meta("escape", [length: 1, constructable: false], :static)
  def named_meta("freeze"), do: meta("freeze", [length: 1, constructable: false], :static)

  def named_meta("preventExtensions"),
    do: meta("preventExtensions", [length: 1, constructable: false], :static)

  def named_meta("seal"), do: meta("seal", [length: 1, constructable: false], :static)
  def named_meta("isFrozen"), do: meta("isFrozen", [length: 1, constructable: false], :static)
  def named_meta("isSealed"), do: meta("isSealed", [length: 1, constructable: false], :static)

  def named_meta("isExtensible"),
    do: meta("isExtensible", [length: 1, constructable: false], :static)

  def named_meta("fromEntries"),
    do: meta("fromEntries", [length: 1, constructable: false], :static)

  def named_meta("__defineGetter__"),
    do: meta("__defineGetter__", [length: 2, constructable: false], :proto)

  def named_meta("__defineSetter__"),
    do: meta("__defineSetter__", [length: 2, constructable: false], :proto)

  def named_meta("__lookupGetter__"),
    do: meta("__lookupGetter__", [length: 1, constructable: false], :proto)

  def named_meta("__lookupSetter__"),
    do: meta("__lookupSetter__", [length: 1, constructable: false], :proto)

  def named_meta("get __proto__"),
    do: meta("get __proto__", [length: 0, constructable: false], :proto)

  def named_meta("set __proto__"),
    do: meta("set __proto__", [length: 1, constructable: false], :proto)

  def named_meta("call"), do: meta("call", [length: 1, constructable: false], :proto)
  def named_meta("apply"), do: meta("apply", [length: 2, constructable: false], :proto)
  def named_meta("bind"), do: meta("bind", [length: 1, constructable: false], :proto)

  def named_meta("[Symbol.hasInstance]"),
    do: meta("[Symbol.hasInstance]", [length: 1, constructable: false], :proto)

  def named_meta("setTime"), do: meta("setTime", [length: 1, constructable: false], :proto)

  def named_meta("setFullYear"),
    do: meta("setFullYear", [length: 3, constructable: false], :proto)

  def named_meta("setMonth"), do: meta("setMonth", [length: 2, constructable: false], :proto)
  def named_meta("setDate"), do: meta("setDate", [length: 1, constructable: false], :proto)
  def named_meta("setHours"), do: meta("setHours", [length: 4, constructable: false], :proto)
  def named_meta("setMinutes"), do: meta("setMinutes", [length: 3, constructable: false], :proto)
  def named_meta("setSeconds"), do: meta("setSeconds", [length: 2, constructable: false], :proto)

  def named_meta("setMilliseconds"),
    do: meta("setMilliseconds", [length: 1, constructable: false], :proto)

  def named_meta("setUTCFullYear"),
    do: meta("setUTCFullYear", [length: 3, constructable: false], :proto)

  def named_meta("setUTCMonth"),
    do: meta("setUTCMonth", [length: 2, constructable: false], :proto)

  def named_meta("setUTCDate"), do: meta("setUTCDate", [length: 1, constructable: false], :proto)

  def named_meta("setUTCHours"),
    do: meta("setUTCHours", [length: 4, constructable: false], :proto)

  def named_meta("setUTCMinutes"),
    do: meta("setUTCMinutes", [length: 3, constructable: false], :proto)

  def named_meta("setUTCSeconds"),
    do: meta("setUTCSeconds", [length: 2, constructable: false], :proto)

  def named_meta("setUTCMilliseconds"),
    do: meta("setUTCMilliseconds", [length: 1, constructable: false], :proto)

  def named_meta("getTime"), do: meta("getTime", [length: 0, constructable: false], :proto)

  def named_meta("getFullYear"),
    do: meta("getFullYear", [length: 0, constructable: false], :proto)

  def named_meta("getMonth"), do: meta("getMonth", [length: 0, constructable: false], :proto)
  def named_meta("getDate"), do: meta("getDate", [length: 0, constructable: false], :proto)
  def named_meta("getHours"), do: meta("getHours", [length: 0, constructable: false], :proto)
  def named_meta("getMinutes"), do: meta("getMinutes", [length: 0, constructable: false], :proto)
  def named_meta("getSeconds"), do: meta("getSeconds", [length: 0, constructable: false], :proto)

  def named_meta("getMilliseconds"),
    do: meta("getMilliseconds", [length: 0, constructable: false], :proto)

  def named_meta("getDay"), do: meta("getDay", [length: 0, constructable: false], :proto)

  def named_meta("getTimezoneOffset"),
    do: meta("getTimezoneOffset", [length: 0, constructable: false], :proto)

  def named_meta("getUTCFullYear"),
    do: meta("getUTCFullYear", [length: 0, constructable: false], :proto)

  def named_meta("getUTCMonth"),
    do: meta("getUTCMonth", [length: 0, constructable: false], :proto)

  def named_meta("getUTCDate"), do: meta("getUTCDate", [length: 0, constructable: false], :proto)
  def named_meta("getUTCDay"), do: meta("getUTCDay", [length: 0, constructable: false], :proto)

  def named_meta("getUTCHours"),
    do: meta("getUTCHours", [length: 0, constructable: false], :proto)

  def named_meta("getUTCMinutes"),
    do: meta("getUTCMinutes", [length: 0, constructable: false], :proto)

  def named_meta("getUTCSeconds"),
    do: meta("getUTCSeconds", [length: 0, constructable: false], :proto)

  def named_meta("getUTCMilliseconds"),
    do: meta("getUTCMilliseconds", [length: 0, constructable: false], :proto)

  def named_meta("valueOf"), do: meta("valueOf", [length: 0, constructable: false], :proto)
  def named_meta("toString"), do: meta("toString", [length: 0, constructable: false], :proto)
  def named_meta("toReversed"), do: meta("toReversed", [length: 0, constructable: false], :proto)
  def named_meta("toSorted"), do: meta("toSorted", [length: 1, constructable: false], :proto)
  def named_meta("toSpliced"), do: meta("toSpliced", [length: 2, constructable: false], :proto)
  def named_meta("with"), do: meta("with", [length: 2, constructable: false], :proto)

  def named_meta("toISOString"),
    do: meta("toISOString", [length: 0, constructable: false], :proto)

  def named_meta("toJSON"), do: meta("toJSON", [length: 1, constructable: false], :proto)

  def named_meta("toDateString"),
    do: meta("toDateString", [length: 0, constructable: false], :proto)

  def named_meta("toTimeString"),
    do: meta("toTimeString", [length: 0, constructable: false], :proto)

  def named_meta("toUTCString"),
    do: meta("toUTCString", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleString"),
    do: meta("toLocaleString", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleDateString"),
    do: meta("toLocaleDateString", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleTimeString"),
    do: meta("toLocaleTimeString", [length: 0, constructable: false], :proto)

  def named_meta("now"), do: meta("now", [length: 0, constructable: false], :static)
  def named_meta("parse"), do: meta("parse", [length: 1, constructable: false], :static)
  def named_meta("UTC"), do: meta("UTC", [length: 7, constructable: false], :static)

  def named_meta("isFinite"), do: meta("isFinite", [length: 1, constructable: false], :static)
  def named_meta("isInteger"), do: meta("isInteger", [length: 1, constructable: false], :static)
  def named_meta("isNaN"), do: meta("isNaN", [length: 1, constructable: false], :static)

  def named_meta("isSafeInteger"),
    do: meta("isSafeInteger", [length: 1, constructable: false], :static)

  def named_meta("toFixed"), do: meta("toFixed", [length: 1, constructable: false], :proto)

  def named_meta("toExponential"),
    do: meta("toExponential", [length: 1, constructable: false], :proto)

  def named_meta("toPrecision"),
    do: meta("toPrecision", [length: 1, constructable: false], :proto)

  def named_meta("parseFloat"), do: meta("parseFloat", [length: 1, constructable: false], :static)
  def named_meta("parseInt"), do: meta("parseInt", [length: 2, constructable: false], :static)

  def named_meta("charAt"), do: meta("charAt", [length: 1, constructable: false], :proto)
  def named_meta("charCodeAt"), do: meta("charCodeAt", [length: 1, constructable: false], :proto)

  def named_meta("codePointAt"),
    do: meta("codePointAt", [length: 1, constructable: false], :proto)

  def named_meta("indexOf"), do: meta("indexOf", [length: 1, constructable: false], :proto)

  def named_meta("lastIndexOf"),
    do: meta("lastIndexOf", [length: 1, constructable: false], :proto)

  def named_meta("includes"), do: meta("includes", [length: 1, constructable: false], :proto)
  def named_meta("startsWith"), do: meta("startsWith", [length: 1, constructable: false], :proto)
  def named_meta("endsWith"), do: meta("endsWith", [length: 1, constructable: false], :proto)
  def named_meta("slice"), do: meta("slice", [length: 2, constructable: false], :proto)
  def named_meta("subarray"), do: meta("subarray", [length: 2, constructable: false], :proto)
  def named_meta("splice"), do: meta("splice", [length: 2, constructable: false], :proto)
  def named_meta("substring"), do: meta("substring", [length: 2, constructable: false], :proto)
  def named_meta("substr"), do: meta("substr", [length: 2, constructable: false], :proto)
  def named_meta("split"), do: meta("split", [length: 2, constructable: false], :proto)

  def named_meta("[Symbol.split]"),
    do: meta("[Symbol.split]", [length: 2, constructable: false], :proto)

  def named_meta("trim"), do: meta("trim", [length: 0, constructable: false], :proto)
  def named_meta("trimStart"), do: meta("trimStart", [length: 0, constructable: false], :proto)
  def named_meta("trimEnd"), do: meta("trimEnd", [length: 0, constructable: false], :proto)

  def named_meta("toUpperCase"),
    do: meta("toUpperCase", [length: 0, constructable: false], :proto)

  def named_meta("toLowerCase"),
    do: meta("toLowerCase", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleUpperCase"),
    do: meta("toLocaleUpperCase", [length: 0, constructable: false], :proto)

  def named_meta("toLocaleLowerCase"),
    do: meta("toLocaleLowerCase", [length: 0, constructable: false], :proto)

  def named_meta("repeat"), do: meta("repeat", [length: 1, constructable: false], :proto)
  def named_meta("padStart"), do: meta("padStart", [length: 1, constructable: false], :proto)
  def named_meta("padEnd"), do: meta("padEnd", [length: 1, constructable: false], :proto)
  def named_meta("replace"), do: meta("replace", [length: 2, constructable: false], :proto)

  def named_meta("[Symbol.replace]"),
    do: meta("[Symbol.replace]", [length: 2, constructable: false], :proto)

  def named_meta("replaceAll"), do: meta("replaceAll", [length: 2, constructable: false], :proto)
  def named_meta("match"), do: meta("match", [length: 1, constructable: false], :proto)

  def named_meta("[Symbol.match]"),
    do: meta("[Symbol.match]", [length: 1, constructable: false], :proto)

  def named_meta("matchAll"), do: meta("matchAll", [length: 1, constructable: false], :proto)

  def named_meta("[Symbol.matchAll]"),
    do: meta("[Symbol.matchAll]", [length: 1, constructable: false], :proto)

  def named_meta("search"), do: meta("search", [length: 1, constructable: false], :proto)

  def named_meta("[Symbol.search]"),
    do: meta("[Symbol.search]", [length: 1, constructable: false], :proto)

  def named_meta("normalize"), do: meta("normalize", [length: 0, constructable: false], :proto)
  def named_meta("concat"), do: meta("concat", [length: 1, constructable: false], :proto)

  def named_meta("localeCompare"),
    do: meta("localeCompare", [length: 1, constructable: false], :proto)

  def named_meta("at"), do: meta("at", [length: 1, constructable: false], :proto)

  def named_meta("isWellFormed"),
    do: meta("isWellFormed", [length: 0, constructable: false], :proto)

  def named_meta("toWellFormed"),
    do: meta("toWellFormed", [length: 0, constructable: false], :proto)

  def named_meta("fromCharCode"),
    do: meta("fromCharCode", [length: 1, constructable: false], :static)

  def named_meta("fromCodePoint"),
    do: meta("fromCodePoint", [length: 1, constructable: false], :static)

  def named_meta("raw"), do: meta("raw", [length: 1, constructable: false], :static)

  def named_meta("[Symbol.iterator]"),
    do: meta("[Symbol.iterator]", [length: 0, constructable: false], :proto)

  def named_meta("get flags"), do: meta("get flags", [length: 0, constructable: false], :proto)

  def named_meta("get hasIndices"),
    do: meta("get hasIndices", [length: 0, constructable: false], :proto)

  def named_meta("get global"), do: meta("get global", [length: 0, constructable: false], :proto)

  def named_meta("get ignoreCase"),
    do: meta("get ignoreCase", [length: 0, constructable: false], :proto)

  def named_meta("get multiline"),
    do: meta("get multiline", [length: 0, constructable: false], :proto)

  def named_meta("get dotAll"), do: meta("get dotAll", [length: 0, constructable: false], :proto)

  def named_meta("get unicode"),
    do: meta("get unicode", [length: 0, constructable: false], :proto)

  def named_meta("get unicodeSets"),
    do: meta("get unicodeSets", [length: 0, constructable: false], :proto)

  def named_meta("get sticky"), do: meta("get sticky", [length: 0, constructable: false], :proto)

  def named_meta("exec"), do: meta("exec", [length: 1, constructable: false], :proto)
  def named_meta("test"), do: meta("test", [length: 1, constructable: false], :proto)

  def named_meta("push"), do: meta("push", [length: 1, constructable: false], :proto)
  def named_meta("pop"), do: meta("pop", [length: 0, constructable: false], :proto)
  def named_meta("shift"), do: meta("shift", [length: 0, constructable: false], :proto)
  def named_meta("unshift"), do: meta("unshift", [length: 1, constructable: false], :proto)
  def named_meta("map"), do: meta("map", [length: 1, constructable: false], :proto)
  def named_meta("filter"), do: meta("filter", [length: 1, constructable: false], :proto)
  def named_meta("reduce"), do: meta("reduce", [length: 1, constructable: false], :proto)

  def named_meta("reduceRight"),
    do: meta("reduceRight", [length: 1, constructable: false], :proto)

  def named_meta("forEach"), do: meta("forEach", [length: 1, constructable: false], :proto)
  def named_meta("some"), do: meta("some", [length: 1, constructable: false], :proto)
  def named_meta("every"), do: meta("every", [length: 1, constructable: false], :proto)
  def named_meta("find"), do: meta("find", [length: 1, constructable: false], :proto)
  def named_meta("findIndex"), do: meta("findIndex", [length: 1, constructable: false], :proto)
  def named_meta("findLast"), do: meta("findLast", [length: 1, constructable: false], :proto)

  def named_meta("findLastIndex"),
    do: meta("findLastIndex", [length: 1, constructable: false], :proto)

  def named_meta("sort"), do: meta("sort", [length: 1, constructable: false], :proto)
  def named_meta("reverse"), do: meta("reverse", [length: 0, constructable: false], :proto)
  def named_meta("join"), do: meta("join", [length: 1, constructable: false], :proto)
  def named_meta("fill"), do: meta("fill", [length: 1, constructable: false], :proto)
  def named_meta("copyWithin"), do: meta("copyWithin", [length: 2, constructable: false], :proto)
  def named_meta("flat"), do: meta("flat", [length: 0, constructable: false], :proto)
  def named_meta("flatMap"), do: meta("flatMap", [length: 1, constructable: false], :proto)
  def named_meta("drop"), do: meta("drop", [length: 1, constructable: false], :proto)
  def named_meta("take"), do: meta("take", [length: 1, constructable: false], :proto)
  def named_meta("toArray"), do: meta("toArray", [length: 0, constructable: false], :proto)
  def named_meta("zip"), do: meta("zip", [length: 1, constructable: false], :static)
  def named_meta("zipKeyed"), do: meta("zipKeyed", [length: 1, constructable: false], :static)
  def named_meta("from"), do: meta("from", [length: 1, constructable: false], :static)
  def named_meta("fromAsync"), do: meta("fromAsync", [length: 1, constructable: false], :static)
  def named_meta("of"), do: meta("of", [length: 0, constructable: false], :static)
  def named_meta("isArray"), do: meta("isArray", [length: 1, constructable: false], :static)
  def named_meta("groupBy"), do: meta("groupBy", [length: 2, constructable: false], :static)
  def named_meta("get"), do: meta("get", [length: 1, constructable: false], :proto)
  def named_meta("set"), do: meta("set", [length: 2, constructable: false], :proto)
  def named_meta("has"), do: meta("has", [length: 1, constructable: false], :proto)
  def named_meta("then"), do: meta("then", [length: 2, constructable: false], :proto)
  def named_meta("catch"), do: meta("catch", [length: 1, constructable: false], :proto)
  def named_meta("finally"), do: meta("finally", [length: 1, constructable: false], :proto)
  def named_meta("resolve"), do: meta("resolve", [length: 1, constructable: false], :static)
  def named_meta("reject"), do: meta("reject", [length: 1, constructable: false], :static)
  def named_meta("all"), do: meta("all", [length: 1, constructable: false], :static)
  def named_meta("allKeyed"), do: meta("allKeyed", [length: 1, constructable: false], :static)
  def named_meta("allSettled"), do: meta("allSettled", [length: 1, constructable: false], :static)

  def named_meta("allSettledKeyed"),
    do: meta("allSettledKeyed", [length: 1, constructable: false], :static)

  def named_meta("any"), do: meta("any", [length: 1, constructable: false], :static)
  def named_meta("race"), do: meta("race", [length: 1, constructable: false], :static)
  def named_meta("try"), do: meta("try", [length: 1, constructable: false], :static)

  def named_meta("withResolvers"),
    do: meta("withResolvers", [length: 0, constructable: false], :static)

  def named_meta("__promiseCapabilityExecutor"),
    do: meta("__promiseCapabilityExecutor", [length: 2, constructable: false], :static)

  def named_meta("isError"), do: meta("isError", [length: 1, constructable: false], :static)

  def named_meta(name)
      when name in [
             "getBigInt64",
             "getBigUint64",
             "getFloat16",
             "getFloat32",
             "getFloat64",
             "getInt8",
             "getInt16",
             "getInt32",
             "getUint8",
             "getUint16",
             "getUint32"
           ],
      do: meta(name, [length: 1, constructable: false], :proto)

  def named_meta(name)
      when name in [
             "setBigInt64",
             "setBigUint64",
             "setFloat16",
             "setFloat32",
             "setFloat64",
             "setInt8",
             "setInt16",
             "setInt32",
             "setUint8",
             "setUint16",
             "setUint32"
           ],
      do: meta(name, [length: 2, constructable: false], :proto)

  def named_meta("next"), do: meta("next", [length: 0, constructable: false], :proto)
  def named_meta("delete"), do: meta("delete", [length: 1, constructable: false], :proto)
  def named_meta("clear"), do: meta("clear", [length: 0, constructable: false], :proto)
  def named_meta("deref"), do: meta("deref", [length: 0, constructable: false], :proto)
  def named_meta("register"), do: meta("register", [length: 2, constructable: false], :proto)
  def named_meta("unregister"), do: meta("unregister", [length: 1, constructable: false], :proto)

  def named_meta("getOrInsert"),
    do: meta("getOrInsert", [length: 2, constructable: false], :proto)

  def named_meta("getOrInsertComputed"),
    do: meta("getOrInsertComputed", [length: 2, constructable: false], :proto)

  def named_meta("add"), do: meta("add", [length: 1, constructable: false], :proto)
  def named_meta("difference"), do: meta("difference", [length: 1, constructable: false], :proto)

  def named_meta("intersection"),
    do: meta("intersection", [length: 1, constructable: false], :proto)

  def named_meta("union"), do: meta("union", [length: 1, constructable: false], :proto)

  def named_meta("symmetricDifference"),
    do: meta("symmetricDifference", [length: 1, constructable: false], :proto)

  def named_meta("isSubsetOf"), do: meta("isSubsetOf", [length: 1, constructable: false], :proto)

  def named_meta("isSupersetOf"),
    do: meta("isSupersetOf", [length: 1, constructable: false], :proto)

  def named_meta("isDisjointFrom"),
    do: meta("isDisjointFrom", [length: 1, constructable: false], :proto)

  def named_meta("hasOwnProperty"),
    do: meta("hasOwnProperty", [length: 1, constructable: false], :proto)

  def named_meta("isPrototypeOf"),
    do: meta("isPrototypeOf", [length: 1, constructable: false], :proto)

  def named_meta("propertyIsEnumerable"),
    do: meta("propertyIsEnumerable", [length: 1, constructable: false], :proto)

  def named_meta(_), do: nil

  defmacro __using__(_opts) do
    quote do
      @behaviour QuickBEAM.VM.Runtime.BuiltinObject

      import QuickBEAM.VM.Builtin,
        only: [
          proto: 2,
          proto: 3,
          static: 2,
          static: 3,
          static_val: 2,
          defintrinsic: 2,
          defintrinsic: 3,
          prototype_methods: 1,
          static_methods: 1,
          js_object: 2,
          build_methods: 1,
          build_object: 1,
          object: 1,
          object: 2,
          builtin_definition: 2,
          constructor: 2,
          constructor: 3,
          arg: 2,
          arg: 3,
          argv: 2,
          builtin: 2,
          builtin: 3,
          builtin_args: 2,
          builtin_receiver: 2,
          builtin_this: 2,
          iterator_from: 1
        ]

      Module.register_attribute(__MODULE__, :__has_proto, accumulate: false)
      Module.register_attribute(__MODULE__, :__has_static, accumulate: false)
      Module.register_attribute(__MODULE__, :__static_names, accumulate: true)
      Module.register_attribute(__MODULE__, :ecma, accumulate: false)
      Module.register_attribute(__MODULE__, :annex, accumulate: false)
      @before_compile QuickBEAM.VM.Builtin
    end
  end

  @doc "Emits fallback clauses for modules that define prototype or static properties."
  defmacro __before_compile__(env) do
    has_proto = Module.get_attribute(env.module, :__has_proto)
    has_static = Module.get_attribute(env.module, :__has_static)

    static_names =
      Module.get_attribute(env.module, :__static_names) |> Enum.reverse() |> Enum.uniq()

    proto_fallback =
      if has_proto do
        quote do
          def proto_property(_), do: :undefined
          def proto_property_meta(_), do: nil
          def proto_property_spec(_), do: nil
        end
      end

    static_fallback =
      if has_static do
        quote do
          def static_property(_), do: :undefined
          def static_property_meta(_), do: nil
          def static_property_spec(_), do: nil
        end
      end

    static_names_fun =
      if has_static do
        quote do
          def static_property_names, do: unquote(Macro.escape(static_names))
        end
      end

    [proto_fallback, static_fallback, static_names_fun]
    |> Enum.reject(&is_nil/1)
    |> case do
      [] -> nil
      blocks -> {:__block__, [], blocks}
    end
  end

  # ── Module-level dispatch macros ──

  def opts_with_builtin_attrs(opts, ecma, annex) do
    opts
    |> put_attr(:ecma, ecma)
    |> put_attr(:annex, annex)
  end

  defp put_attr(opts, _key, nil), do: opts
  defp put_attr(opts, key, value), do: Keyword.put_new(opts, key, value)

  @doc "Defines a prototype property as a JavaScript builtin function."
  defmacro proto(name, opts \\ [], do: body) do
    quote do
      @__has_proto true

      def proto_property(unquote(name)) do
        unquote(build_builtin(name, body))
      end

      def proto_property_spec(unquote(name)) do
        QuickBEAM.VM.Builtin.function_spec(
          unquote(name),
          QuickBEAM.VM.Builtin.opts_with_builtin_attrs(
            unquote(Macro.escape(opts)),
            @ecma,
            @annex
          ),
          :prototype
        )
      end

      def proto_property_meta(unquote(name)) do
        proto_property_spec(unquote(name))
        |> QuickBEAM.VM.Builtin.function_meta()
      end

      @ecma nil
      @annex nil
    end
  end

  @doc "Defines a constructor/static property as a JavaScript builtin function."
  defmacro static(name, opts \\ [], do: body) do
    quote do
      @__has_static true
      @__static_names unquote(name)

      def static_property(unquote(name)) do
        unquote(build_builtin(name, body))
      end

      def static_property_spec(unquote(name)) do
        QuickBEAM.VM.Builtin.function_spec(
          unquote(name),
          QuickBEAM.VM.Builtin.opts_with_builtin_attrs(
            unquote(Macro.escape(opts)),
            @ecma,
            @annex
          ),
          :static
        )
      end

      def static_property_meta(unquote(name)) do
        static_property_spec(unquote(name))
        |> QuickBEAM.VM.Builtin.function_meta()
      end

      @ecma nil
      @annex nil
    end
  end

  @doc "Defines a constructor/static property as a fixed value."
  defmacro static_val(name, value) do
    quote do
      @__has_static true
      @__static_names unquote(name)
      def static_property(unquote(name)), do: unquote(value)
    end
  end

  @doc "Defines an ECMAScript intrinsic constructor. Alias for `builtin_definition/2`."
  defmacro defintrinsic(name, opts) do
    case Keyword.pop(opts, :do) do
      {nil, opts} ->
        build_builtin_definition(name, opts, __CALLER__)

      {block, opts} ->
        opts = Keyword.merge(opts, parse_intrinsic_block(block))
        build_builtin_definition(name, opts, __CALLER__)
    end
  end

  defmacro defintrinsic(name, opts, do: block) do
    opts = Keyword.merge(opts, parse_intrinsic_block(block))
    build_builtin_definition(name, opts, __CALLER__)
  end

  @doc "Defines prototype methods using contextual `method` entries."
  defmacro prototype(do: block) do
    build_contextual_methods(block, :proto)
  end

  @doc "Defines prototype methods using contextual `method` entries without colliding with local `prototype/1` functions."
  defmacro prototype_methods(do: block) do
    build_contextual_methods(block, :proto)
  end

  @doc "Defines constructor/static methods using contextual `method` entries."
  defmacro statics(do: block) do
    build_contextual_methods(block, :static)
  end

  @doc "Defines constructor/static methods using contextual `method` entries."
  defmacro static_methods(do: block) do
    build_contextual_methods(block, :static)
  end

  @doc "Defines declarative installation metadata for a JavaScript builtin."
  defmacro builtin_definition(name, opts) do
    build_builtin_definition(name, opts, __CALLER__)
  end

  defp build_builtin_definition(name, opts, caller) do
    constructor = Keyword.fetch!(opts, :constructor)
    length = Keyword.get(opts, :length)
    phase = Keyword.get(opts, :phase, :runtime)
    module = Keyword.get(opts, :module, caller.module)
    prototype_parent = Keyword.get(opts, :prototype_parent, :object)
    constructor_descriptor = Keyword.get(opts, :constructor_descriptor, %{})
    prototype_descriptor = Keyword.get(opts, :prototype_descriptor, %{})
    prototype_properties = Keyword.get(opts, :prototype_properties, [])
    constructable? = Keyword.get(opts, :constructable, true)
    intrinsic_key = Keyword.get(opts, :intrinsic_key)
    after_install = Keyword.get(opts, :after_install)
    auto_install? = Keyword.get(opts, :auto_install?, true)

    quote do
      def builtin_definition do
        struct!(QuickBEAM.VM.Builtin.Definition, %{
          name: unquote(name),
          constructor: unquote(constructor),
          length: unquote(length),
          phase: unquote(phase),
          module: unquote(module),
          prototype_parent: unquote(prototype_parent),
          constructor_descriptor:
            Map.merge(
              unquote(Macro.escape(PropertyDescriptor.constructor())),
              unquote(Macro.escape(constructor_descriptor))
            ),
          prototype_descriptor:
            Map.merge(
              unquote(Macro.escape(PropertyDescriptor.prototype())),
              unquote(Macro.escape(prototype_descriptor))
            ),
          prototype_properties: unquote(prototype_properties),
          constructable?: unquote(constructable?),
          intrinsic_key: unquote(intrinsic_key),
          ecma:
            Keyword.get(
              QuickBEAM.VM.Builtin.opts_with_builtin_attrs(
                unquote(Macro.escape(opts)),
                @ecma,
                @annex
              ),
              :ecma
            ),
          annex:
            Keyword.get(
              QuickBEAM.VM.Builtin.opts_with_builtin_attrs(
                unquote(Macro.escape(opts)),
                @ecma,
                @annex
              ),
              :annex
            ),
          after_install: unquote(after_install),
          auto_install?: unquote(auto_install?)
        })
      end

      @ecma nil
      @annex nil
    end
  end

  defp build_contextual_methods(block, target) do
    block
    |> contextual_methods(target)
    |> block_from_entries()
  end

  defp parse_intrinsic_block(block) do
    block
    |> normalize_block()
    |> Enum.flat_map(fn
      {:install_with, _, [callback]} ->
        [after_install: callback]

      {:phase, _, [phase]} ->
        [phase: phase]

      {:constructor, _, [opts, [do: body]]} when is_list(opts) ->
        Keyword.put(opts, :constructor, build_constructor_callback(body))

      {:constructor, _, [[do: body]]} ->
        [constructor: build_constructor_callback(body)]

      {:constructor, _, [callback, opts]} when is_list(opts) ->
        Keyword.put(opts, :constructor, callback)

      {:constructor, _, [callback]} ->
        [constructor: callback]

      _ ->
        []
    end)
  end

  defp build_constructor_callback(body) do
    quote do
      fn var!(args), var!(this) ->
        _ = var!(args)
        _ = var!(this)
        unquote(body)
      end
    end
  end

  defp contextual_methods(block, target) do
    block
    |> normalize_block()
    |> Enum.map(fn
      {:@, _, _} = attr ->
        attr

      {:method, meta, [name, [do: body]]} ->
        {target, meta, [name, [do: body]]}

      {:method, meta, [name, opts, [do: body]]} ->
        {target, meta, [name, opts, [do: body]]}

      other ->
        other
    end)
  end

  defp block_from_entries([entry]), do: entry
  defp block_from_entries(entries), do: {:__block__, [], entries}

  # ── Named object macro ──

  @doc "Defines a named builtin object exported by `object/0`."
  defmacro js_object(name, do: block) do
    map_entries = build_map_entries(normalize_block(block))

    quote do
      def object do
        {:builtin, unquote(name), %{unquote_splicing(map_entries)}}
      end
    end
  end

  # ── Inline map/list macros ──

  @doc "Builds a raw map of builtin method/property entries."
  defmacro build_methods(do: block) do
    map_entries = build_map_entries(normalize_block(block))
    quote do: %{unquote_splicing(map_entries)}
  end

  defmacro object(opts \\ [], do: block) do
    map_entries = build_map_entries(normalize_block(block))
    heap? = Keyword.get(opts, :heap, true)

    if heap? do
      quote do
        QuickBEAM.VM.Heap.wrap(%{unquote_splicing(map_entries)})
      end
    else
      quote do: %{unquote_splicing(map_entries)}
    end
  end

  @doc "Builds a heap-wrapped object from builtin method/property entries."
  defmacro build_object(do: block) do
    map_entries = build_map_entries(normalize_block(block))

    quote do
      QuickBEAM.VM.Heap.wrap(%{unquote_splicing(map_entries)})
    end
  end

  @doc "Registers a JavaScript constructor and optional prototype definition."
  defmacro constructor(name, callback) do
    build_constructor(name, callback, [], nil)
  end

  defmacro constructor(name, callback, do: block) do
    {proto_entries, parent} = parse_constructor_block(block)
    build_constructor(name, callback, proto_entries, parent)
  end

  # ── Shared builders ──

  defp build_constructor(name, callback, proto_entries, parent) do
    proto_map_entries = build_map_entries(proto_entries)

    quote do
      QuickBEAM.VM.Runtime.ConstructorRegistry.register(
        unquote(name),
        unquote(callback),
        %{unquote_splicing(proto_map_entries)},
        unquote(parent)
      )
    end
  end

  defp build_builtin(name, body, opts \\ []) do
    quote do
      QuickBEAM.VM.Builtin.builtin(
        unquote(name),
        fn var!(args), var!(this) ->
          _ = var!(args)
          _ = var!(this)
          unquote(body)
        end,
        unquote(Macro.escape(opts))
      )
    end
  end

  defp normalize_block({:__block__, _, entries}), do: entries
  defp normalize_block(single), do: [single]

  defp build_map_entries(entries) do
    {map_entries, _pending_opts} =
      Enum.reduce(entries, {[], []}, fn
        {:@, _, [{:ecma, _, [ecma]}]}, {built, pending_opts} ->
          {built, Keyword.put(pending_opts, :ecma, ecma)}

        {:@, _, [{:annex, _, [annex]}]}, {built, pending_opts} ->
          {built, Keyword.put(pending_opts, :annex, annex)}

        {:@, _, [{:doc, _, [_doc]}]}, {built, pending_opts} ->
          {built, pending_opts}

        entry, {built, pending_opts} ->
          {[build_map_entry(entry, pending_opts) | built], []}
      end)

    Enum.reverse(map_entries)
  end

  defp parse_constructor_block(block) do
    block
    |> normalize_block()
    |> Enum.reduce({[], nil}, fn
      {:proto, _, [[do: proto_block]]}, {_entries, _parent} ->
        parse_proto_block(proto_block)

      entry, {entries, parent} ->
        {[entry | entries], parent}
    end)
    |> then(fn {entries, parent} -> {Enum.reverse(entries), parent} end)
  end

  defp parse_proto_block(block) do
    block
    |> normalize_block()
    |> Enum.reduce({[], nil}, fn
      {:extends, _, [parent]}, {entries, _parent} -> {entries, parent}
      entry, {entries, parent} -> {[entry | entries], parent}
    end)
    |> then(fn {entries, parent} -> {Enum.reverse(entries), parent} end)
  end

  defp build_map_entry(entry, pending_opts)

  defp build_map_entry({:method, _, [name, [do: body]]}, pending_opts) do
    {name, build_builtin(name, body, pending_opts)}
  end

  defp build_map_entry({:method, _, [name, opts, [do: body]]}, pending_opts) when is_list(opts) do
    {name, build_builtin(name, body, Keyword.merge(pending_opts, opts))}
  end

  defp build_map_entry({:args_method, _, [name, callback]}, _pending_opts) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_args(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:receiver_method, _, [name, callback]}, _pending_opts) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_receiver(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:this_method, _, [name, callback]}, _pending_opts) do
    {name, quote(do: QuickBEAM.VM.Builtin.builtin_this(unquote(name), unquote(callback)))}
  end

  defp build_map_entry({:symbol_method, _, [name, [do: body]]}, pending_opts) do
    {{:symbol, name}, build_builtin("[#{name}]", body, pending_opts)}
  end

  defp build_map_entry({:accessor, _, [name, [do: block]]}, pending_opts) do
    {getter, setter} = build_accessor_parts(name, block, pending_opts)
    {name, quote(do: {:accessor, unquote(getter), unquote(setter)})}
  end

  defp build_map_entry({:getter, _, [name, [do: body]]}, pending_opts) do
    {name, quote(do: {:accessor, unquote(build_builtin("get #{name}", body, pending_opts)), nil})}
  end

  defp build_map_entry({:val, _, [name, value]}, _pending_opts) do
    {name, value}
  end

  defp build_map_entry({:prop, _, [name, value]}, _pending_opts) do
    {name, value}
  end

  defp build_accessor_parts(name, block, pending_opts) do
    block
    |> normalize_block()
    |> Enum.reduce({nil, nil}, fn
      {:get, _, [[do: body]]}, {_getter, setter} ->
        {build_builtin("get #{name}", body, pending_opts), setter}

      {:set, _, [[do: body]]}, {getter, _setter} ->
        {getter, build_builtin("set #{name}", body, pending_opts)}
    end)
  end

  # ── Runtime helpers ──

  @doc "Returns a positional argument with a JavaScript `:undefined` default."
  def arg(args, index, default \\ :undefined), do: Enum.at(args, index, default)

  def argv(args, defaults) do
    defaults
    |> Enum.with_index()
    |> Enum.map(fn {default, index} -> arg(args, index, default) end)
  end

  @doc "Wraps a two-arity callback in the VM builtin tuple representation."
  def builtin(name, callback, opts \\ [])

  def builtin(name, callback, %Meta{} = meta) when is_function(callback, 2) do
    {:builtin, name, callback}
    |> put_builtin_metadata(meta)
  end

  def builtin(name, callback, opts) when is_function(callback, 2) do
    function = {:builtin, name, callback}

    case opts do
      [] -> function
      _ -> put_builtin_metadata(function, meta(name, opts))
    end
  end

  def builtin_args(name, callback) when is_function(callback, 1) do
    {:builtin, name, fn args, _this -> callback.(args) end}
  end

  def builtin_receiver(name, callback) when is_function(callback, 2) do
    {:builtin, name, fn args, this -> callback.(this, args) end}
  end

  @doc "Wraps a receiver-only callback in the VM builtin tuple representation."
  def builtin_this(name, callback) when is_function(callback, 1) do
    {:builtin, name, fn _args, this -> callback.(this) end}
  end

  def put_if_present(map, _key, nil), do: map
  def put_if_present(map, key, value), do: Map.put(map, key, value)

  def iterator_from(items) do
    iter = QuickBEAM.VM.Heap.wrap_iterator(items)

    with {:obj, ref} <- iter do
      QuickBEAM.VM.Heap.update_obj(ref, %{}, fn map ->
        Map.put(
          map,
          {:symbol, "Symbol.iterator"},
          builtin("[Symbol.iterator]", fn _, this -> this end)
        )
      end)
    end

    iter
  end

  # ── Runtime dispatch ──

  import QuickBEAM.VM.Heap.Keys, only: [proxy_target: 0]
  alias QuickBEAM.VM.{Heap, JSThrow}

  @doc "Dispatches a VM callable value to its underlying Elixir callback."
  def call({:builtin, name, _cb}, _args, _this)
      when name in ~w(Map Set WeakMap WeakSet WeakRef FinalizationRegistry DataView Promise) do
    JSThrow.type_error!("Constructor #{name} requires 'new'")
  end

  def call({:builtin, _, cb}, args, this) when is_function(cb, 2), do: cb.(args, this)

  def call({:bound, _, inner, _, _}, args, this), do: call(inner, args, this)

  def call({:obj, _} = obj, _args, _this) do
    if obj == Heap.get_func_proto(), do: :undefined, else: JSThrow.type_error!("not a function")
  end

  def call(f, args, _this) when is_function(f, 2), do: f.(args, nil)

  def call(f, args, _this) when is_function(f, 1), do: f.(args)

  def call(f, args, _this) when is_function(f), do: apply(f, args)

  def call(_, _, _),
    do: JSThrow.type_error!("not a function")

  @doc "Returns a built-in function's JavaScript name, if present."
  def name({:builtin, name, _}), do: name
  def name(_), do: nil

  @doc "Returns whether a VM value can be called as a JavaScript function."
  def callable?(%QuickBEAM.VM.Function{}), do: true

  def callable?({:closure, _, %QuickBEAM.VM.Function{}}), do: true

  def callable?({:builtin, _, callback}) when is_function(callback), do: true
  def callable?({:builtin, _, _}), do: false

  def callable?({:bound, _, _, _, _}), do: true

  def callable?({:obj, ref} = obj) do
    obj == Heap.get_func_proto() or
      case Heap.get_obj(ref, %{}) do
        %{proxy_target() => target} -> callable?(target)
        _ -> false
      end
  end

  def callable?(f) when is_function(f), do: true

  def callable?(_), do: false
end
